import React, { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Button } from 'primereact/button';
import { BreadCrumb } from 'primereact/breadcrumb';
import { Card } from 'primereact/card';
import { Checkbox } from 'primereact/checkbox';
import { Dialog } from 'primereact/dialog';
import { Dropdown } from 'primereact/dropdown';
import { InputText } from 'primereact/inputtext';
import { Menu } from 'primereact/menu';
import { Message } from 'primereact/message';
import { TabMenu } from 'primereact/tabmenu';
import { PrototypeProvider } from './prototype-provider.jsx';
import { NavigationShell } from './navigation-shell.jsx';
import { initialDataset, childrenFor, filterChildren, filterProjects, filterTasks, referencesFor, imagesFor, materialsFor, foldersFor, folderTrail, projectFolderScope, sectionFolderScope, isProjectReadOnly, createFolder, renameFolder, moveFolder, moveResources, reorderResources, listKey, projectKey, taskKey, referenceKey, imageKey, taskStateOptions, taskTypeOptions, projectTabs, resolveContextRoute } from './project-context-model.mjs';
import './project-context.css';
const memoryKey = 'cm-project-context-preview-v3';
const moduleLabels = { production: '生产', training: '训练' };
const stateLabels = { active:'正常',archived:'已归档',unsubmitted:'未提交',submitted:'已提交',pending:'等待中',running:'运行中',paused:'已暂停',completed:'已完成',failed:'失败',cancelled:'已取消' };
const taskLabels = { 'image-generation':'图片生成','material-generation':'素材生成','lora-training':'LoRA 训练' };
const childTabFor = p => p.module === 'production' ? 'sections' : 'compositions';
const childLabelFor = p => p.module === 'production' ? '小节' : '构图';
const breadcrumbSlots = { root:{style:{padding:0,border:0,background:'transparent'}},menu:{style:{flexWrap:'wrap',gap:'8px'}} };
const plainActivation = e => !e.defaultPrevented && (e.button == null || e.button === 0) && !e.metaKey && !e.ctrlKey && !e.shiftKey && !e.altKey;
function readMemory() {
  const empty = { current: '', activeModule: 'production', scroll: {}, lastLists: {}, focus: {}, viewFilters: {}, dataset: initialDataset };
  try { const saved = JSON.parse(sessionStorage.getItem(memoryKey) || '{}'); return { ...empty, ...saved, dataset: saved.dataset?.references ? saved.dataset : initialDataset }; } catch { return empty; }
}
function persist(memory) { try { sessionStorage.setItem(memoryKey, JSON.stringify(memory)); } catch { /* Navigation remains usable when storage is unavailable. */ } }
function useContextNavigation() {
  const [memory] = useState(readMemory);
  const [dataset, setDataset] = useState(memory.dataset);
  const dataRef = useRef(dataset);
  const [route, setRoute] = useState(() => resolveContextRoute(location.hash || memory.current || 'production/tasks', dataset));
  const current = useRef(route);
  const restoring = useRef(false);
  function capture() { if (!restoring.current) memory.scroll[current.current.key] = window.scrollY; }
  function apply(next) {
    restoring.current = true; current.current = next; memory.current = next.key;
    if (next.module) memory.activeModule = next.module;
    if (next.kind === 'list') memory.lastLists[next.rootKey] = next.key;
    persist(memory); setRoute(next);
  }
  function go(key, { replace = false, focusId } = {}) {
    if (focusId) memory.focus[current.current.key] = focusId;
    capture(); const next = resolveContextRoute(key, dataRef.current);
    if (location.hash !== `#${next.key}`) history[replace ? 'replaceState' : 'pushState'](null, '', `#${next.key}`);
    apply(next);
  }
  function follow(event, key, focusId) { if (plainActivation(event)) { event.preventDefault(); go(key, { focusId }); } }
  function updateDataset(next) { dataRef.current = next; memory.dataset = next; setDataset(next); capture(); apply(resolveContextRoute(current.current.key, next)); }
  function reset() {
    Object.assign(memory, { scroll: {}, focus: {}, lastLists: {}, viewFilters: {}, dataset: initialDataset });
    dataRef.current = initialDataset; setDataset(initialDataset);
    const next = resolveContextRoute('production/projects', initialDataset);
    history.replaceState(null, '', `#${next.key}`); apply(next);
  }
  useLayoutEffect(() => {
    if (route.project && route.tab) memory.viewFilters[`${route.module}/${route.project.id}/${route.tab}`] = route.filters;
    if (location.hash !== `#${route.key}`) history.replaceState(null, '', `#${route.key}`);
    window.scrollTo({ top: Number(memory.scroll[route.key]) || 0, behavior: 'instant' });
    const target = memory.focus[route.key];
    if (target) document.querySelector(`[data-context-link="${CSS.escape(target)}"]`)?.focus({ preventScroll: true });
    restoring.current = false; persist(memory);
  }, [route]);
  useEffect(() => {
    const previous = history.scrollRestoration; history.scrollRestoration = 'manual';
    const onHistory = () => { const next = resolveContextRoute(location.hash, dataRef.current); if (next.key !== current.current.key || next.notice) { capture(); apply(next); } };
    const onHide = () => { capture(); persist(memory); };
    window.addEventListener('popstate', onHistory); window.addEventListener('hashchange', onHistory);
    window.addEventListener('scroll', capture, { passive: true }); window.addEventListener('pagehide', onHide);
    return () => { window.removeEventListener('popstate', onHistory); window.removeEventListener('hashchange', onHistory); window.removeEventListener('scroll', capture); window.removeEventListener('pagehide', onHide); history.scrollRestoration = previous; };
  }, []);
  return { route, memory, dataset, go, follow, updateDataset, reset };
}
function ContextLink({navigation,to,identity,children,...props}) { return <a {...props} href={`#${to}`} draggable={false} data-context-link={identity} onClick={e=>navigation.follow(e,to,identity)}>{children}</a>; }
function Photo({src,name,label,empty='暂无图片',large=false}) {
  const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);
  return <figure className={`ctx-photo${large?' ctx-photo-large':''}`}>{src&&!failed?<><img src={src} alt={name} loading="lazy" width="600" height="400" draggable={false} onError={()=>setFailed(true)}/><figcaption>{label}</figcaption></>:<div className="ctx-no-photo"><i className="pi pi-image" aria-hidden="true"/><span>{failed?'图片暂不可用':empty}</span></div>}</figure>;
}
function MoreActions({label,items}) {const menu=useRef(null);return <><Button text plain icon="pi pi-ellipsis-h" aria-label={`${label}的操作`} onClick={e=>menu.current.toggle(e)} aria-haspopup="menu"/><Menu popup ref={menu} model={items}/></>;}
function SectionTitle({title,count,children}) {return <div className="ctx-section-title"><h2>{title}{count!=null&&<span> · {count}</span>}</h2>{children}</div>;}
function Empty({children}) {return <div className="ctx-empty"><i className="pi pi-images" aria-hidden="true"/><p>{children}</p></div>;}
function readonlyRecord(record,context,dataset) {return isProjectReadOnly(context.kind==='project'?record:context.project||dataset.projects.find(p=>p.id===record.projectId));}
const folderLocation=(scope,id,dataset)=>['根目录',...folderTrail(scope,id,dataset).map(f=>f.name)].join(' / ');
function collectionKey(navigation,project,folder,filters=navigation.route.filters) {return project?projectKey(project,childTabFor(project),navigation.route.from,'',{...filters,folder},navigation.dataset):listKey(navigation.route.module,'projects',{...filters,folder});}
function Filters({navigation,kind='project'}) {
  const {route,dataset}=navigation,[query,setQuery]=useState(route.filters.q||'');useEffect(()=>setQuery(route.filters.q||''),[route.key]);
  const tasks=kind==='task',label=tasks?'搜索任务或项目':kind==='child'?`搜索${childLabelFor(route.project)}`:'搜索项目';
  function apply(filters){navigation.go(route.project?projectKey(route.project,route.tab,route.from,'',filters,dataset):listKey(route.module,route.section,filters),{replace:true});}
  const options=tasks?[{label:'全部状态',value:'all'},...taskStateOptions(route.module)]:[{label:'全部状态',value:'all'},{label:'正常',value:'active'},{label:'已归档',value:'archived'}];
  return <form className="ctx-toolbar" onSubmit={e=>{e.preventDefault();apply({...route.filters,q:query});}}><div className="ctx-search"><InputText aria-label={label} placeholder={label} value={query} onChange={e=>setQuery(e.target.value)}/><Button type="submit" icon="pi pi-search" aria-label="搜索"/></div>{kind!=='child'&&<Dropdown className="ctx-status-filter" value={route.filters.status||'all'} options={options} onChange={e=>apply({...route.filters,q:query,status:e.value})} aria-label={tasks?'任务状态':'项目状态'}/>} {tasks&&taskTypeOptions(route.module).length>1&&<Dropdown className="ctx-status-filter" value={route.filters.type||'all'} options={[{label:'全部类型',value:'all'},...taskTypeOptions(route.module)]} onChange={e=>apply({...route.filters,q:query,type:e.value})} aria-label="任务类型"/>}{(query||(route.filters.status&&route.filters.status!=='all')||(route.filters.type&&route.filters.type!=='all'))&&<Button type="button" text label="清除筛选" onClick={()=>apply({folder:route.filters.folder})}/>}</form>;
}
function useOperations(navigation) {
  const [dialog,setDialog]=useState(null),[name,setName]=useState(''),[destination,setDestination]=useState(''),[error,setError]=useState(''),[feedback,setFeedback]=useState(null);
  useEffect(()=>setFeedback(null),[navigation.route.key]);
  function open(action){setDialog(action);setName(action.kind==='rename'?action.records[0].name:'');setDestination(action.parentId&&action.parentId!=='all'?action.parentId:'');setError('');}
  function commit(action,message,href,done){try{navigation.updateDataset(action());done?.();setFeedback({text:message,href});return true;}catch(e){setFeedback({text:e.message,error:true});return false;}}
  function submit(e){e?.preventDefault();try{const {dataset}=navigation,record=dialog.records?.[0];let next;if(dialog.kind==='create')next=createFolder(dataset,{scope:dialog.scope,parentId:dialog.parentId||'',name});if(dialog.kind==='rename')next=renameFolder(dataset,{id:record.id,name});if(dialog.kind==='move')next=dialog.context.kind==='folder'?moveFolder(dataset,{id:record.id,parentId:destination}):moveResources(dataset,{...dialog.context,ids:dialog.records.map(r=>r.id),folderId:destination});navigation.updateDataset(next);dialog.done?.();setDialog(null);setFeedback({text:dialog.kind==='move'?`已移动 ${dialog.records.filter(r=>(r.folderId??r.parentId??'')!==destination).length} 项至${next.folders.find(f=>f.id===destination)?.name||'根目录'}`:dialog.kind==='create'?`已创建“${name.trim()}”`:`已重命名为“${name.trim()}”`,href:dialog.kind==='move'?dialog.context.hrefFor(destination):null});}catch(err){setError(err.message);}}
  function menu(record,context,records){if(readonlyRecord(record,context,navigation.dataset))return [];const sortable=records.filter(r=>!readonlyRecord(r,context,navigation.dataset)),index=sortable.findIndex(r=>r.id===record.id),items=[];if(context.kind==='folder')items.push({label:'重命名',icon:'pi pi-pencil',command:()=>open({kind:'rename',records:[record],scope:context.scope})});if(context.scope)items.push({label:'移动到文件夹',icon:'pi pi-folder-open',command:()=>open({kind:'move',records:[record],context,scope:context.scope,parentId:record.folderId??record.parentId})});if(context.reorder)items.push({label:'上移',icon:'pi pi-arrow-up',disabled:index===0,command:()=>commit(()=>reorderResources(navigation.dataset,{...context,ids:[record.id],beforeId:sortable[index-1]?.id}),'顺序已更新')},{label:'下移',icon:'pi pi-arrow-down',disabled:index===sortable.length-1,command:()=>commit(()=>reorderResources(navigation.dataset,{...context,ids:[record.id],beforeId:sortable[index+2]?.id}),'顺序已更新')});return items;}
  const current=navigation.dataset.folders.find(f=>f.id===destination),choices=dialog?foldersFor(dialog.scope,destination,navigation.dataset).filter(f=>dialog.context?.kind!=='folder'||!folderTrail(dialog.scope,f.id,navigation.dataset).some(parent=>parent.id===dialog.records[0].id)):[];
  const sameTarget=dialog?.kind==='move'&&dialog.records.every(r=>(r.folderId??r.parentId??'')===destination);
  const ui=<>{feedback&&<div className="ctx-feedback" role="status"><Message severity={feedback.error?'error':'success'} text={feedback.text}/>{feedback.href&&<ContextLink navigation={navigation} to={feedback.href} className="ctx-inline-link">查看目标文件夹<i className="pi pi-arrow-right" aria-hidden="true"/></ContextLink>}</div>}<Dialog className="ctx-dialog" header={dialog?.kind==='move'?`移动 ${dialog.records.length} 项`:dialog?.kind==='rename'?'重命名文件夹':'新建文件夹'} visible={!!dialog} onHide={()=>setDialog(null)} draggable={false} blockScroll footer={<div className="ctx-dialog-actions"><Button text label="取消" onClick={()=>setDialog(null)}/><Button label={dialog?.kind==='move'?'移动到此处':'保存'} disabled={dialog?.kind==='move'?sameTarget:!name.trim()} onClick={submit}/></div>}>{dialog?.kind==='move'?<><p className="ctx-muted">{dialog.records.map(r=>r.name).join('、')}</p><div className="ctx-dialog-location">根目录{folderTrail(dialog.scope,destination,navigation.dataset).map(f=>` / ${f.name}`).join('')}</div><div className="ctx-destination-list">{destination&&<Button text plain icon="pi pi-arrow-left" label="上一级" onClick={()=>setDestination(current?.parentId||'')}/>} {choices.map(f=><Button key={f.id} text plain icon="pi pi-folder" label={f.name} onClick={()=>setDestination(f.id)}/>)}{!choices.length&&<p className="ctx-muted">当前位置没有子文件夹。</p>}</div></>:<form className="ctx-dialog-form" onSubmit={submit}><label htmlFor="context-folder-name">文件夹名称</label><InputText id="context-folder-name" autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></form>}{error&&<Message severity="error" text={error}/>}</Dialog></>;
  return {open,commit,menu,ui};
}
function useDragOperations(navigation,operations) {
  const [payload,setPayload]=useState(null),[target,setTarget]=useState(null),[hint,setHint]=useState(''),current=useRef(null);
  function clear(){current.current=null;setPayload(null);setTarget(null);setHint('');}
  useEffect(()=>clear(),[navigation.route.key]);
  useEffect(()=>{const escape=e=>{if(e.key==='Escape')clear();};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[]);
  function start(e,record,context,ids,done){if(readonlyRecord(record,context,navigation.dataset)){e.preventDefault();return;}const value={...context,ids:ids.includes(record.id)?ids:[record.id],done};current.current=value;setPayload(value);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-cm-resources',JSON.stringify({kind:value.kind,ids:value.ids}));setHint(`正在拖动 ${value.ids.length} 项；拖入文件夹${context.reorder?'或拖到卡片前后排序':''}，Esc 取消。`);}
  function folderProps(scope,folderId,label,hrefFor){const eligible=payload&&payload.scope===scope&&payload.ids.some(id=>navigation.dataset[payload.kind==='project'?'projects':'children'].find(r=>r.id===id)?.folderId!==folderId);return {className:eligible?'ctx-droppable':'',onDragOver:e=>{const p=current.current;if(!p)return;e.preventDefault();const valid=p.scope===scope&&p.scope&&p.ids.some(id=>navigation.dataset[p.kind==='project'?'projects':'children'].find(r=>r.id===id)?.folderId!==folderId);e.dataTransfer.dropEffect=valid?'move':'none';setTarget(valid?`folder-${folderId}`:null);setHint(valid?`移入“${label}”：${p.ids.length} 项`:'当前位置不可接收这些内容。');},onDragLeave:e=>{if(!e.currentTarget.contains(e.relatedTarget)){setTarget(null);setHint(current.current?.reorder?'拖入目标文件夹，或拖到卡片前后排序。':'拖入高亮文件夹；Esc 取消。');}},onDrop:e=>{const p=current.current;if(!p)return;e.preventDefault();e.stopPropagation();const count=p.ids.filter(id=>navigation.dataset[p.kind==='project'?'projects':'children'].find(r=>r.id===id)?.folderId!==folderId).length;if(p.scope===scope&&p.scope&&count)operations.commit(()=>moveResources(navigation.dataset,{...p,folderId}),`已移动 ${count} 项至${label}`,hrefFor(folderId),p.done);clear();}};}
  function cardProps(record,context,records,ids,done){return {draggable:!readonlyRecord(record,context,navigation.dataset)&&(!!context.scope||context.reorder),onDragStart:e=>start(e,record,context,ids,done),onDragEnd:clear,onDragOver:e=>{const p=current.current;if(!p||!context.reorder)return;e.preventDefault();const valid=p.kind===context.kind&&p.module===context.module&&p.projectId===context.projectId&&p.folderId===context.folderId&&!p.ids.includes(record.id)&&!readonlyRecord(record,context,navigation.dataset);e.dataTransfer.dropEffect=valid?'move':'none';if(!valid){setTarget(null);setHint('此处不可排序，请选择同一范围内的其他可编辑卡片。');return;}const after=e.clientY>e.currentTarget.getBoundingClientRect().top+e.currentTarget.getBoundingClientRect().height/2;setTarget(`${after?'after':'before'}-${record.id}`);setHint(`排在“${record.name}”${after?'之后':'之前'}`);},onDrop:e=>{const p=current.current;if(!p||!context.reorder||!target?.endsWith(record.id))return;e.preventDefault();e.stopPropagation();const index=records.findIndex(r=>r.id===record.id),beforeId=target.startsWith('after-')?records.slice(index+1).find(r=>!p.ids.includes(r.id)&&!readonlyRecord(r,context,navigation.dataset))?.id:record.id;operations.commit(()=>reorderResources(navigation.dataset,{...context,ids:p.ids,beforeId}),'顺序已更新',null,p.done);clear();}};}
  return {payload,target,hint,folderProps,cardProps};
}
function ResourceCard({navigation,record,href,photoLabel,detail,footer,photo=record.photo,empty,actions,selection,dragProps={},dragClass='',linkLabel}) {
  return <li {...dragProps} data-resource-id={record.id} className={`ctx-resource ${dragClass}${selection?.checked?' is-selected':''}`}><Card className="ctx-card" pt={{body:{style:{padding:0}},content:{style:{padding:0}}}}><ContextLink navigation={navigation} to={href} identity={record.id} className="ctx-card-link" aria-label={linkLabel||`打开${record.name}`}><Photo src={photo} name={`${record.name} · ${photoLabel}`} label={photoLabel} empty={empty}/><div className="ctx-card-copy"><h3>{record.name}</h3><p>{detail}</p></div></ContextLink>{selection&&<label className="ctx-card-select" htmlFor={`select-${record.id}`}><Checkbox inputId={`select-${record.id}`} aria-label={`选择${record.name}`} checked={selection.checked} disabled={selection.disabled} onChange={selection.onChange}/><span>{selection.disabled?'只读':'选择'}</span></label>}<div className="ctx-card-footer"><span>{footer}</span>{dragProps.draggable&&<span className="ctx-drag-handle" aria-label={`可拖动${record.name}`} title="拖动卡片；键盘与触屏可使用操作菜单"><i className="pi pi-arrows-alt" aria-hidden="true"/></span>}{actions?.length>0&&<MoreActions label={record.name} items={actions}/>}</div></Card></li>;
}
function Collection({navigation,operations,drag,records,context,render,label}) {
  const [selected,setSelected]=useState([]);useEffect(()=>setSelected([]),[navigation.route.key]);
  const mutable=records.filter(r=>!readonlyRecord(r,context,navigation.dataset)),picked=records.filter(r=>selected.includes(r.id)),done=()=>setSelected([]);
  const selectedIndexes=mutable.map((r,i)=>selected.includes(r.id)?i:-1).filter(i=>i>=0),first=Math.min(...selectedIndexes),last=Math.max(...selectedIndexes);
  function shift(up){operations.commit(()=>reorderResources(navigation.dataset,{...context,ids:mutable.filter(r=>selected.includes(r.id)).map(r=>r.id),beforeId:up?mutable[first-1]?.id:mutable[last+2]?.id}),`已调整 ${selected.length} 项顺序`);}

  return <>{(context.scope||context.reorder)&&mutable.length>0&&<div className="ctx-selection-bar"><span>{selected.length?`已选 ${selected.length} 项`:'选择后可批量操作'}</span><Button text label={selected.length===mutable.length?'取消全选':'全选可编辑项'} onClick={()=>setSelected(selected.length===mutable.length?[]:mutable.map(r=>r.id))}/>{selected.length>0&&context.reorder&&<><Button text icon="pi pi-arrow-up" label="上移" disabled={first===0} onClick={()=>shift(true)}/><Button text icon="pi pi-arrow-down" label="下移" disabled={last===mutable.length-1} onClick={()=>shift(false)}/></>}{selected.length>0&&context.scope&&<Button outlined icon="pi pi-folder-open" label="移动到" onClick={()=>operations.open({kind:'move',records:picked,context,scope:context.scope,parentId:context.folderId,done})}/>}</div>}{records.length?<ul className="ctx-grid" aria-label={label}>{records.map(record=><ResourceCard key={record.id} navigation={navigation} record={record} {...render(record)} actions={operations.menu(record,context,records)} selection={(context.scope||context.reorder)?{checked:selected.includes(record.id),disabled:readonlyRecord(record,context,navigation.dataset),onChange:e=>setSelected(e.checked?[...selected,record.id]:selected.filter(id=>id!==record.id))}:null} dragProps={drag.cardProps(record,context,records,selected,done)} dragClass={drag.target===`before-${record.id}`?'is-drop-before':drag.target===`after-${record.id}`?'is-drop-after':''}/>)}</ul>:<Empty>当前范围没有匹配内容。</Empty>}</>;
}
function FolderBrowser({navigation,project,operations,drag}) {
  const {route,dataset}=navigation,scope=project?sectionFolderScope(project):projectFolderScope(route.module);if(!scope)return null;
  const currentId=route.filters.folder||'',all=currentId==='all',readonly=isProjectReadOnly(project),hrefFor=folder=>collectionKey(navigation,project,folder);
  const trail=[{id:'',name:'根目录'},...folderTrail(scope,all?'':currentId,dataset)],folders=foldersFor(scope,all?'':currentId,dataset),context={kind:'folder',module:route.module,projectId:project?.id,project,scope,folderId:all?'':currentId,hrefFor,reorder:true};
  function contents(folder){const records=project?childrenFor(project,dataset):dataset.projects.filter(p=>p.module===route.module);return records.filter(r=>folderTrail(scope,r.folderId,dataset).some(f=>f.id===folder.id));}
  return <><div className="ctx-folder-bar"><ContextLink navigation={navigation} to={hrefFor('all')} className={`ctx-inline-link${all?' is-current':''}`}>全部{project?'小节':'项目'}</ContextLink><div className="ctx-folder-path"><BreadCrumb aria-label="文件夹路径" pt={breadcrumbSlots} model={trail.map(f=>({label:f.name,template:()=>{const drop=readonly?{}:drag.folderProps(scope,f.id,f.name,hrefFor);return <span {...drop} className={`ctx-crumb-drop ${drop.className||''}${drag.target===`folder-${f.id}`?' is-drop-folder':''}`}><ContextLink navigation={navigation} to={hrefFor(f.id)}>{f.name}</ContextLink></span>;}}))}/></div>{!readonly&&<Button outlined icon="pi pi-folder-plus" label="新建文件夹" onClick={()=>operations.open({kind:'create',scope,parentId:all?'':currentId})}/>}</div>{all&&<p className="ctx-muted ctx-range-note">包含子文件夹内容；进入具体文件夹后可调整其中的小节顺序。</p>}{folders.length>0&&<ul className="ctx-grid ctx-folder-grid" aria-label="文件夹">{folders.map(folder=>{const records=contents(folder),photo=records.find(r=>r.photo)?.photo,drop=readonly?{}:drag.folderProps(scope,folder.id,folder.name,hrefFor);return <li key={folder.id} {...drop} className={`ctx-folder-card ${drop.className||''}${drag.target===`folder-${folder.id}`?' is-drop-folder':''}`} data-folder-id={folder.id}><ContextLink navigation={navigation} to={hrefFor(folder.id)} identity={folder.id} aria-label={`进入文件夹 ${folder.name}`}><span className="ctx-folder-cover">{photo?<img src={photo} alt="" width="48" height="48" draggable={false}/>:<i className="pi pi-folder" aria-hidden="true"/>}</span><span className="ctx-folder-copy"><strong>{folder.name}</strong><small>{records.length} 个{project?'小节':'项目'}</small></span></ContextLink>{!readonly&&<MoreActions label={folder.name} items={operations.menu(folder,context,folders)}/>}</li>;})}</ul>}</>;
}
function Projects({navigation,operations,drag}) {
  const {route,dataset}=navigation,records=filterProjects(route.module,{...route.filters,folder:route.module==='production'?(route.filters.folder||''):'all'},dataset),context={kind:'project',module:route.module,scope:projectFolderScope(route.module),folderId:route.filters.folder||'',hrefFor:folder=>collectionKey(navigation,null,folder),reorder:route.module==='training'&&!route.filters.q&&route.filters.status!=='archived'};
  return <><Filters navigation={navigation}/><FolderBrowser navigation={navigation} operations={operations} drag={drag}/><SectionTitle title={route.filters.folder==='all'?'全部项目':'当前范围项目'} count={records.length}/><Collection navigation={navigation} operations={operations} drag={drag} records={records} context={context} label="项目卡片" render={p=>({href:projectKey(p,'overview',route.key,'',{},dataset),photoLabel:'最近结果',detail:`${childrenFor(p,dataset).length} 个${childLabelFor(p)}`,footer:stateLabels[p.state]+(p.module==='production'&&route.filters.folder==='all'?` · ${folderLocation(projectFolderScope(p.module),p.folderId,dataset)}`:'')})}/></>;
}
function ChildCards({navigation,operations,drag,all=false}) {
  const {route,dataset}=navigation,p=route.project,label=childLabelFor(p),records=all?childrenFor(p,dataset):filterChildren(p,{...route.filters,folder:p.module==='production'?(route.filters.folder||''):'all'},dataset),context={kind:'child',module:p.module,projectId:p.id,project:p,scope:all?'':sectionFolderScope(p),folderId:route.filters.folder||'',hrefFor:folder=>collectionKey(navigation,p,folder),reorder:!all&&!route.filters.q&&(p.module==='training'||route.filters.folder!=='all')};
  return <><SectionTitle title={all?`全部${label}`:`当前范围${label}`} count={records.length}>{all&&<ContextLink navigation={navigation} to={collectionKey(navigation,p,'all',{})} className="ctx-inline-link">查看全部<i className="pi pi-arrow-right" aria-hidden="true"/></ContextLink>}</SectionTitle><Collection navigation={navigation} operations={operations} drag={drag} records={records} context={context} label={`${label}卡片`} render={child=>({href:projectKey(p,childTabFor(p),route.from,child.id,all?{folder:'all'}:route.filters,dataset),photoLabel:p.module==='production'?'最近结果':'代表图',empty:p.module==='training'?'尚未选择代表图':'暂无结果',detail:p.module==='training'?`${dataset.images.filter(i=>i.childId===child.id).length} 张候选 · ${child.trainingCaption?'已有说明文本':'缺少说明文本'}`:`${dataset.tasks.filter(t=>t.childId===child.id).length} 次任务`,footer:(isProjectReadOnly(p)?'已归档 · 只读':p.module==='production'?'图片小节':'构图工作区')+(p.module==='production'&&(all||route.filters.folder==='all')?` · ${folderLocation(sectionFolderScope(p),child.folderId,dataset)}`:'')})}/></>;
}
function TaskCards({navigation,project,child}) {
  const {route,dataset}=navigation,tasks=filterTasks(route.module,route.section==='tasks'||route.tab==='tasks'?route.filters:{},dataset).filter(t=>(!project||t.projectId===project.id)&&(!child||t.childId===child.id));
  return <><SectionTitle title={child?'相关任务':'任务'} count={tasks.length}/>{tasks.length?<ul className="ctx-grid" aria-label="任务卡片">{tasks.map(t=>{const owner=dataset.projects.find(p=>p.id===t.projectId),source=childrenFor(owner,dataset).find(c=>c.id===t.childId),training=t.type==='lora-training';return <ResourceCard key={t.id} navigation={navigation} record={t} href={taskKey(t,route.key,dataset)} linkLabel={`打开${t.name} · ${owner.name}`} photo={training?t.samples?.[0]?.photo:t.photo||t.sourcePhoto} photoLabel={training?'本次训练输入快照':t.photo?'本次输出':'输入参考 · 尚无输出'} empty={training?'没有训练样本':'尚无输出图片'} detail={`${owner.name}${source?` · ${source.name}`:''}${training?` · ${t.samples?.length||0} 份训练样本`:''}`} footer={`${taskLabels[t.type]} · ${stateLabels[t.state]}`}/>;})}</ul>:<Empty>当前范围没有任务。</Empty>}</>;
}
function ImageCards({navigation,images,from=navigation.route.key,label='图片卡片'}) {return images.length?<ul className="ctx-grid" aria-label={label}>{images.map(img=><ResourceCard key={img.id} navigation={navigation} record={img} href={imageKey(img,from,navigation.dataset)} photoLabel="生成结果" detail={navigation.dataset.children.find(c=>c.id===img.childId)?.name||'项目图片'} footer={img.taskId?'查看结果与来源任务':'手动上传结果'}/>)}</ul>:<Empty>当前范围没有图片结果。</Empty>;}
function ProjectTabs({navigation}) {
  const {route,dataset,memory}=navigation,tabs=projectTabs[route.module],index=tabs.findIndex(t=>t.id===route.tab),key=t=>projectKey(route.project,t,route.from,'',memory.viewFilters[`${route.module}/${route.project.id}/${t}`]||{},dataset);
  return <TabMenu className={`ctx-${route.module}`} model={tabs.map(t=>({id:t.id,label:t.label,url:`#${key(t.id)}`}))} activeIndex={index} onTabChange={({originalEvent,index:i})=>{if(plainActivation(originalEvent)){originalEvent.preventDefault();navigation.go(key(tabs[i].id));}}} pt={{menu:{className:'ctx-tab-list','aria-label':'项目页签',style:{background:'transparent',padding:0}},action:({context})=>({'aria-current':context.index===index?'page':undefined,style:{padding:'10px 8px',minHeight:'40px',fontWeight:500,justifyContent:'center',background:'transparent',color:context.index===index?'var(--accent)':'var(--nav-secondary)',borderColor:context.index===index?'var(--accent)':'var(--nav-border)',transition:'color var(--duration-quick) var(--ease-out), border-color var(--duration-quick) var(--ease-out)'}}),label:{style:{whiteSpace:'nowrap'}}}}/>;
}
function ProjectView({navigation,operations,drag}) {
  const {route,dataset}=navigation,p=route.project;
  return <><ProjectTabs navigation={navigation}/><div className="ctx-view-body">
    {route.tab===childTabFor(p)?<><Filters navigation={navigation} kind="child"/><FolderBrowser navigation={navigation} project={p} operations={operations} drag={drag}/><ChildCards navigation={navigation} operations={operations} drag={drag}/></>:route.tab==='overview'?<><ChildCards navigation={navigation} operations={operations} drag={drag} all/><TaskCards navigation={navigation} project={p}/></>:route.tab==='tasks'?<><Filters navigation={navigation} kind="task"/><TaskCards navigation={navigation} project={p}/></>:route.tab==='images'?<><SectionTitle title="项目图片" count={imagesFor(p,dataset).length}/><ImageCards navigation={navigation} images={imagesFor(p,dataset)}/></>:route.tab==='references'?<><SectionTitle title="项目参考图" count={referencesFor(p,dataset).length}/><ul className="ctx-grid" aria-label="参考图卡片">{referencesFor(p,dataset).map(ref=><ResourceCard key={ref.id} navigation={navigation} record={ref} href={referenceKey(ref,route.key,dataset)} photoLabel="输入参考图" detail={ref.description} footer="查看参考图与使用位置"/>)}</ul></>:route.tab==='materials'?<><SectionTitle title="训练素材"/><ul className="ctx-grid" aria-label="训练素材卡片">{materialsFor(p,dataset).map(m=><ResourceCard key={m.child.id} navigation={navigation} record={m.child} href={projectKey(p,'compositions',route.from,m.child.id,{folder:'all'},dataset)} photo={m.selectedResult?.photo} photoLabel="选中的代表图" empty="尚未选择代表图" detail={`${m.candidateCount} 张候选 · ${m.trainingCaption||'缺少说明文本'}`} footer={!m.selectedResult?'未选图 · 不纳入训练':!m.trainingCaption?'缺说明文本':'可纳入训练'}/>)}</ul></>:<><SectionTitle title="角色档案"/><dl className="ctx-profile">{[['触发词',p.profile?.triggerToken],['角色描述',p.profile?.characterDescription],['图像生产提示词',p.profile?.imageProductionPrompt]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value||'尚未填写'}</dd></div>)}</dl><SectionTitle title="参考图片"/><ul className="ctx-grid">{referencesFor(p,dataset).slice(0,2).map(ref=><ResourceCard key={ref.id} navigation={navigation} record={ref} href={referenceKey(ref,projectKey(p,'references',route.from,'',{},dataset),dataset)} photoLabel="参考图" detail={ref.description} footer="查看参考图"/>)}</ul></>}
  </div></>;
}
function ChildWorkspace({navigation}) {
  const {route,dataset}=navigation,{project:p,child}=route,siblings=childrenFor(p,dataset),index=siblings.findIndex(c=>c.id===child.id),images=imagesFor(p,dataset).filter(i=>i.childId===child.id),training=p.module==='training';
  return <div className="ctx-workspace"><div className="ctx-workspace-heading"><h2>{childLabelFor(p)}工作区</h2><div className="ctx-neighbors">{[-1,1].map(step=>{const sibling=siblings[index+step];return <Button key={step} text plain icon={step<0?'pi pi-angle-left':'pi pi-angle-right'} aria-label={`${step<0?'上':'下'}一个${childLabelFor(p)}`} disabled={!sibling} onClick={()=>navigation.go(projectKey(p,childTabFor(p),route.from,sibling.id,route.filters,dataset))}/>;})}</div></div>{training&&<><SectionTitle title="输入参考图"/><div className="ctx-reference-strip">{(child.inputReferenceIds||[]).map(id=>{const ref=dataset.references.find(r=>r.id===id);return ref?<ContextLink key={id} navigation={navigation} to={referenceKey(ref,route.key,dataset)}><img src={ref.photo} alt={ref.name} width="120" height="80"/><span>{ref.name}</span></ContextLink>:null;})}</div><dl className="ctx-profile"><div><dt>权威说明文本（Caption）</dt><dd>{child.trainingCaption||'尚未填写；选出代表图后补充说明文本。'}</dd></div></dl></>}<SectionTitle title={training?'候选图片':'小节结果'} count={images.length}/><ImageCards navigation={navigation} images={images}/><TaskCards navigation={navigation} project={p} child={child}/></div>;
}
function ResourceDetail({navigation}) {
  const {route,dataset}=navigation,p=route.project,ref=route.reference,img=route.image,record=ref||img,child=img&&dataset.children.find(c=>c.id===img.childId),task=img&&dataset.tasks.find(t=>t.id===img.taskId),uses=ref?childrenFor(p,dataset).filter(c=>c.inputReferenceIds?.includes(ref.id)):[];
  return <div className="ctx-workspace"><Photo src={record.photo} name={record.name} label={ref?'项目输入参考图':'结果图片'} large/>{ref?<><p>{ref.description}</p><SectionTitle title="使用此参考图的构图" count={uses.length}/><div className="ctx-related">{uses.map(c=><ContextLink key={c.id} navigation={navigation} className="ctx-inline-link" to={projectKey(p,'compositions','',c.id,{folder:'all'},dataset)}>{c.name}</ContextLink>)}</div></>:<div className="ctx-related">{child&&<ContextLink navigation={navigation} className="ctx-inline-link" to={projectKey(p,childTabFor(p),'',child.id,{folder:child.folderId},dataset)}>来源{childLabelFor(p)}：{child.name}</ContextLink>}{task&&<ContextLink navigation={navigation} className="ctx-inline-link" to={taskKey(task,route.key,dataset)}>来源任务：{task.name}</ContextLink>}</div>}</div>;
}
function TaskDetail({navigation}) {
  const {route,dataset}=navigation,{task,project:p}=route,training=task.type==='lora-training',child=childrenFor(p,dataset).find(c=>c.id===task.childId),origin=route.from?resolveContextRoute(route.from,dataset):null,listSource=origin?.kind==='list'?origin.key:origin?.from||listKey(task.module,'tasks'),outputs=(task.outputImageIds||[]).map(id=>dataset.images.find(i=>i.id===id)).filter(Boolean);
  return <div className="ctx-workspace"><div className="ctx-related"><ContextLink navigation={navigation} className="ctx-inline-link" to={projectKey(p,'tasks',listSource,'',{},dataset)}>所属项目：{p.name}</ContextLink>{child&&<ContextLink navigation={navigation} className="ctx-inline-link" to={projectKey(p,childTabFor(p),listSource,child.id,{folder:child.folderId},dataset)}>来源{childLabelFor(p)}：{child.name}</ContextLink>}</div><SectionTitle title={taskLabels[task.type]}><span>{stateLabels[task.state]}</span></SectionTitle>{training?<><SectionTitle title="本次训练输入快照" count={task.samples?.length||0}/><ul className="ctx-grid" aria-label="训练输入快照">{(task.samples||[]).map(sample=><li key={sample.id||sample.imageId}><Photo src={sample.photo} name="训练输入样本" label="训练输入快照"/><ContextLink navigation={navigation} className="ctx-inline-link" to={projectKey(p,childTabFor(p),listSource,sample.childId,{folder:'all'},dataset)}>来源构图：{dataset.children.find(c=>c.id===sample.childId)?.name||'查看项目'}</ContextLink><p className="ctx-sample-caption">{sample.caption}</p></li>)}</ul><SectionTitle title="模型产物" count={task.checkpoints?.length||0}/>{task.checkpoints?.length?<ul className="ctx-checkpoints">{task.checkpoints.map(cp=><li key={cp.name}><i className="pi pi-box" aria-hidden="true"/><strong>{cp.name}</strong><span>{cp.step} steps · {cp.state==='removed'?'文件已清理，记录保留':'已保存'}</span></li>)}</ul>:<p className="ctx-muted">{task.state==='running'?'正在训练，尚未保存模型检查点。':'本次没有保存模型检查点；训练输入快照仍可查看。'}</p>}</>:<><SectionTitle title="本次输出" count={outputs.length}/><ImageCards navigation={navigation} images={outputs}/>{task.state==='failed'&&<Message severity="error" text={outputs.length?'部分候选已生成，本次任务仍失败。':'本次生成失败，没有输出图片。'}/>}</>}</div>;
}
function App() {
  const navigation=useContextNavigation(),operations=useOperations(navigation),drag=useDragOperations(navigation,operations),{route,dataset,memory}=navigation,p=route.project,activeModule=route.module||memory.activeModule;
  const source=route.from||listKey(activeModule,route.kind==='task'?'tasks':'projects',p?{folder:p.folderId}:{}),origin=resolveContextRoute(source,dataset),resourceDetail=['reference','image'].includes(route.kind),backKey=route.kind==='child'?(route.collectionKey||projectKey(p,childTabFor(p),route.from,'',route.filters,dataset)):source;
  const backLabel=route.kind==='child'?`返回${childLabelFor(p)}列表`:origin.kind==='child'?`返回${childLabelFor(origin.project)}工作区`:origin.kind==='project'?`返回${projectTabs[origin.module].find(t=>t.id===origin.tab)?.label||'项目'}`:origin.kind==='task'?'返回任务详情':origin.kind==='image'?'返回图片详情':origin.kind==='reference'?'返回参考图详情':origin.section==='tasks'?'返回任务列表':'返回项目列表';
  const crumbs=p?[{label:moduleLabels[activeModule],url:`#${activeModule}/tasks`},{label:'项目',url:`#${listKey(activeModule,'projects',{folder:p.folderId})}`},{label:p.name,url:`#${projectKey(p,'overview',route.from,'',{},dataset)}`},...(['child','reference','image'].includes(route.kind)?[{label:route.title}]:[])].map(item=>item.url?{...item,command:({originalEvent})=>navigation.follow(originalEvent,item.url)}:{...item,template:()=> <span aria-current="page">{item.label}</span>}):[];
  const header=<header className="ctx-page-header">{p&&route.kind!=='task'&&<BreadCrumb aria-label="项目层级" className="ctx-breadcrumb" pt={breadcrumbSlots} model={crumbs}/>}<div className="ctx-title-row"><div><h1>{route.title}</h1><p>交互原型 · 图片与记录均为演示样本</p></div>{p&&<ContextLink navigation={navigation} to={backKey} className="ctx-return"><i className="pi pi-arrow-left" aria-hidden="true"/>{backLabel}</ContextLink>}</div></header>;
  return <NavigationShell route={route} activeModule={activeModule} onNavigate={(key,{originalEvent,source})=>{originalEvent?.preventDefault();navigation.go(source==='module'?key:memory.lastLists[key]||key);}} header={header} contentClassName="ctx-main" className="project-context-preview" reviewLabel="R02-02 · 项目上下文" reviewHref="../../reviews/R02-02.md" previewTitle="项目导航预览设置" previewControls={<p>操作仅保存在本浏览器会话。重置会还原所有演示记录。</p>} onReset={navigation.reset} resetLabel="重置导航与文件夹样本"><div className="ctx-content">{route.notice&&<div className="ctx-route-notice"><Message severity="warn" text={route.notice}/></div>}{isProjectReadOnly(p)&&<div className="ctx-readonly" role="note"><i className="pi pi-lock" aria-hidden="true"/>已归档 · 只读，可浏览保留内容。</div>}{operations.ui}{drag.payload&&<div className="ctx-drag-status" role="status">{drag.hint}</div>}{route.kind==='list'?route.section==='projects'?<Projects navigation={navigation} operations={operations} drag={drag}/>:<><Filters navigation={navigation} kind="task"/><TaskCards navigation={navigation}/></>:route.kind==='task'?<TaskDetail navigation={navigation}/>:resourceDetail?<ResourceDetail navigation={navigation}/>:route.kind==='child'?<ChildWorkspace navigation={navigation}/>:p?<ProjectView navigation={navigation} operations={operations} drag={drag}/>:<Empty>此页面将在对应设计任务中展开。</Empty>}<p className="ctx-footnote">R02-02 · 当前验证对象关系、组织操作与导航恢复。正式编辑与执行在对应业务任务中设计。</p></div></NavigationShell>;
}
createRoot(document.getElementById('root')).render(<PrototypeProvider><App/></PrototypeProvider>);
