import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const POSTGRES_SCHEMA = "prisma/schema.prisma";
const SQLITE_SCHEMA = "prisma/schema.sqlite.prisma";
const OUTPUT_PATH = "docs/prisma-schema-compatibility.md";

type FieldReference = {
  model: string;
  field: string;
  type: string;
  attributes: string;
};

function modelNames(schemaPath: string): string[] {
  return [...readFileSync(schemaPath, "utf8").matchAll(/^model\s+(\w+)\s*\{/gm)]
    .map((match) => match[1])
    .sort((a, b) => a.localeCompare(b));
}

function enumDefinitions(schemaPath: string): Map<string, string[]> {
  const source = readFileSync(schemaPath, "utf8");
  const enums = new Map<string, string[]>();

  for (const match of source.matchAll(/^enum\s+(\w+)\s*\{([\s\S]*?)^}/gm)) {
    const values = match[2]
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("//"));
    enums.set(match[1], values);
  }

  return enums;
}

function modelFields(schemaPath: string): FieldReference[] {
  const source = readFileSync(schemaPath, "utf8");
  const fields: FieldReference[] = [];

  for (const modelMatch of source.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^}/gm)) {
    const model = modelMatch[1];
    for (const line of modelMatch[2].split("\n")) {
      const fieldMatch = line.trim().match(/^(\w+)\s+(\w+\??)\b(.*)$/);
      if (!fieldMatch) {
        continue;
      }
      fields.push({
        model,
        field: fieldMatch[1],
        type: fieldMatch[2],
        attributes: fieldMatch[3].trim(),
      });
    }
  }

  return fields;
}

function ownerDomain(model: string): string {
  if (model.startsWith("Training")) return "training";
  if (model.startsWith("Preset")) return "preset-library";
  if (model.startsWith("ProjectTemplate") || model.startsWith("Template")) return "template-library";
  if (model.startsWith("Project") || model.startsWith("Section") || model === "Run") return "generation-projects";
  if (model === "ImageResult" || model === "TrashRecord" || model === "CensoringTask") return "review-images";
  if (model === "LoraAsset") return "asset-library";
  if (model === "AuditLog" || model === "GpuTaskLock") return "operations";
  return "data-model";
}

function row(model: string): string {
  return [
    `\`${model}\``,
    ownerDomain(model),
    `\`${POSTGRES_SCHEMA}\``,
    `\`${SQLITE_SCHEMA}\``,
    "shared in PostgreSQL and SQLite",
    "keep-compatible; update both schemas or document provider-specific difference",
  ].join(" | ");
}

function enumMappingRow(
  enumName: string,
  values: string[],
  postgresFields: FieldReference[],
  sqliteFields: Map<string, FieldReference>,
): string {
  const postgresFieldNames = postgresFields.map((field) => `\`${field.model}.${field.field}\``).join(", ");
  const sqliteFieldNames = postgresFields
    .map((field) => {
      const sqliteField = sqliteFields.get(`${field.model}.${field.field}`);
      if (!sqliteField) {
        return `\`${field.model}.${field.field}: missing\``;
      }
      const defaultMatch = sqliteField.attributes.match(/@default\(([^)]+)\)/);
      const defaultText = defaultMatch ? ` @default(${defaultMatch[1]})` : "";
      return `\`${field.model}.${field.field}: ${sqliteField.type}${defaultText}\``;
    })
    .join(", ");

  return [
    `\`${enumName}\``,
    values.map((value) => `\`${value}\``).join(", "),
    postgresFieldNames,
    sqliteFieldNames,
    "PostgreSQL uses Prisma enum columns; SQLite stores equivalent strings and must keep values/defaults synchronized.",
  ].join(" | ");
}

const postgresModels = modelNames(POSTGRES_SCHEMA);
const sqliteModels = modelNames(SQLITE_SCHEMA);
const sharedModels = postgresModels.filter((model) => sqliteModels.includes(model));
const postgresOnlyModels = postgresModels.filter((model) => !sqliteModels.includes(model));
const sqliteOnlyModels = sqliteModels.filter((model) => !postgresModels.includes(model));
const postgresEnums = enumDefinitions(POSTGRES_SCHEMA);
const postgresFields = modelFields(POSTGRES_SCHEMA);
const sqliteFields = new Map(modelFields(SQLITE_SCHEMA).map((field) => [`${field.model}.${field.field}`, field]));
const enumRows = [...postgresEnums.entries()].map(([enumName, values]) =>
  enumMappingRow(
    enumName,
    values,
    postgresFields.filter((field) => field.type === enumName),
    sqliteFields,
  ),
);

const output = [
  "# Prisma Schema Compatibility Checklist",
  "",
  "Generated by `scripts/docs/generate-prisma-schema-compatibility.ts`. Re-run after adding, removing, or renaming Prisma models.",
  "",
  "## Shared Models",
  "",
  "| model | owner domain | PostgreSQL schema | SQLite schema | compatibility status | action |",
  "| --- | --- | --- | --- | --- | --- |",
  ...sharedModels.map((model) => `| ${row(model)} |`),
  "",
  "## Provider Enum Mapping",
  "",
  "| enum | PostgreSQL values | PostgreSQL fields | SQLite fields | compatibility action |",
  "| --- | --- | --- | --- | --- |",
  ...enumRows.map((row) => `| ${row} |`),
  "",
  "## Provider-Only Models",
  "",
  postgresOnlyModels.length === 0 ? "- PostgreSQL-only models: none" : `- PostgreSQL-only models: ${postgresOnlyModels.join(", ")}`,
  sqliteOnlyModels.length === 0 ? "- SQLite-only models: none" : `- SQLite-only models: ${sqliteOnlyModels.join(", ")}`,
  "",
  "## Checklist Rule",
  "",
  "- Shared model changes must update both `prisma/schema.prisma` and `prisma/schema.sqlite.prisma` in the same batch.",
  "- Provider-specific differences must be documented in `docs/prisma-provider-matrix.md` or in the batch notes before merging.",
  "- Regenerate both clients with `npm run prisma:generate:all` after schema changes.",
  "",
].join("\n");

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, output);
