import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const POSTGRES_SCHEMA = "prisma/schema.prisma";
const SQLITE_SCHEMA = "prisma/schema.sqlite.prisma";
const OUTPUT_PATH = "docs/prisma-schema-compatibility.md";

function modelNames(schemaPath: string): string[] {
  return [...readFileSync(schemaPath, "utf8").matchAll(/^model\s+(\w+)\s*\{/gm)]
    .map((match) => match[1])
    .sort((a, b) => a.localeCompare(b));
}

function ownerDomain(model: string): string {
  if (model.startsWith("Training")) return "training";
  if (model.startsWith("Preset")) return "preset-library";
  if (model.startsWith("ProjectTemplate") || model.startsWith("Template")) return "template-library";
  if (model.startsWith("Project") || model.startsWith("Section") || model === "Run") return "generation-projects";
  if (model === "ImageResult" || model === "TrashRecord" || model === "CensoringTask") return "review-images";
  if (model === "LoraAsset") return "asset-library";
  if (model === "AuditLog" || model === "GpuTaskLock") return "operations";
  return "data-model";
}

function row(model: string): string {
  return [
    `\`${model}\``,
    ownerDomain(model),
    `\`${POSTGRES_SCHEMA}\``,
    `\`${SQLITE_SCHEMA}\``,
    "shared in PostgreSQL and SQLite",
    "keep-compatible; update both schemas or document provider-specific difference",
  ].join(" | ");
}

const postgresModels = modelNames(POSTGRES_SCHEMA);
const sqliteModels = modelNames(SQLITE_SCHEMA);
const sharedModels = postgresModels.filter((model) => sqliteModels.includes(model));
const postgresOnlyModels = postgresModels.filter((model) => !sqliteModels.includes(model));
const sqliteOnlyModels = sqliteModels.filter((model) => !postgresModels.includes(model));

const output = [
  "# Prisma Schema Compatibility Checklist",
  "",
  "Generated by `scripts/docs/generate-prisma-schema-compatibility.ts`. Re-run after adding, removing, or renaming Prisma models.",
  "",
  "## Shared Models",
  "",
  "| model | owner domain | PostgreSQL schema | SQLite schema | compatibility status | action |",
  "| --- | --- | --- | --- | --- | --- |",
  ...sharedModels.map((model) => `| ${row(model)} |`),
  "",
  "## Provider-Only Models",
  "",
  postgresOnlyModels.length === 0 ? "- PostgreSQL-only models: none" : `- PostgreSQL-only models: ${postgresOnlyModels.join(", ")}`,
  sqliteOnlyModels.length === 0 ? "- SQLite-only models: none" : `- SQLite-only models: ${sqliteOnlyModels.join(", ")}`,
  "",
  "## Checklist Rule",
  "",
  "- Shared model changes must update both `prisma/schema.prisma` and `prisma/schema.sqlite.prisma` in the same batch.",
  "- Provider-specific differences must be documented in `docs/prisma-provider-matrix.md` or in the batch notes before merging.",
  "- Regenerate both clients with `npm run prisma:generate:all` after schema changes.",
  "",
].join("\n");

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, output);
