import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const POSTGRES_SCHEMA = "prisma/schema.prisma";
const SQLITE_SCHEMA = "prisma/schema.sqlite.prisma";
const COMPATIBILITY_DOC = "docs/prisma-schema-compatibility.md";

function modelNames(schemaPath: string) {
  return [...readFileSync(schemaPath, "utf8").matchAll(/^model\s+(\w+)\s*\{/gm)].map((match) => match[1]);
}

function parseChecklistRows() {
  const doc = readFileSync(COMPATIBILITY_DOC, "utf8");
  const rows = new Map<string, string[]>();

  for (const line of doc.split("\n")) {
    if (!line.startsWith("| `")) {
      continue;
    }
    const cells = line
      .split("|")
      .slice(1, -1)
      .map((cell) => cell.trim());
    const model = cells[0]?.replace(/^`|`$/g, "");
    if (model) {
      rows.set(model, cells);
    }
  }

  return { doc, rows };
}

test("Prisma schema compatibility checklist covers every shared model", () => {
  const postgresModels = modelNames(POSTGRES_SCHEMA);
  const sqliteModels = modelNames(SQLITE_SCHEMA);
  const sharedModels = postgresModels.filter((model) => sqliteModels.includes(model)).sort();
  const { doc, rows } = parseChecklistRows();

  assert.match(
    doc,
    /\| model \| owner domain \| PostgreSQL schema \| SQLite schema \| compatibility status \| action \|/,
  );
  assert.equal(sharedModels.length, 54);
  assert.deepEqual(
    sharedModels.filter((model) => !rows.has(model)),
    [],
    "compatibility checklist must include every model shared by both Prisma schemas",
  );

  for (const model of sharedModels) {
    const row = rows.get(model);
    assert.ok(row, `${model} missing from compatibility checklist`);
    assert.equal(row[2], "`prisma/schema.prisma`", `${model} must point to PostgreSQL schema`);
    assert.equal(row[3], "`prisma/schema.sqlite.prisma`", `${model} must point to SQLite schema`);
    assert.match(row[4], /shared/i, `${model} must be marked as shared`);
    assert.match(row[5], /keep-compatible/i, `${model} must have a keep-compatible action`);
  }
});

test("Prisma schema compatibility checklist is generated and indexed", () => {
  const checklist = readFileSync(COMPATIBILITY_DOC, "utf8");
  const index = readFileSync("docs/index.md", "utf8");

  assert.match(checklist, /Generated by `scripts\/docs\/generate-prisma-schema-compatibility\.ts`/);
  assert.match(index, /docs\/prisma-schema-compatibility\.md/);
});
