import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const POSTGRES_SCHEMA = "prisma/schema.prisma";
const SQLITE_SCHEMA = "prisma/schema.sqlite.prisma";
const COMPATIBILITY_DOC = "docs/prisma-schema-compatibility.md";
const RELATION_SCOPE_MODELS = [
  { model: "PresetVariantLink", parentScope: "sourceVariantId" },
  { model: "ProjectPresetBinding", parentScope: "projectId" },
  { model: "ProjectTemplatePresetBinding", parentScope: "projectTemplateId" },
  { model: "SectionPresetBinding", parentScope: "projectSectionId" },
  { model: "TemplateSectionPresetBinding", parentScope: "projectTemplateSectionId" },
  { model: "SectionManualLoraEntry", parentScope: "projectSectionId" },
  { model: "TemplateSectionManualLoraEntry", parentScope: "projectTemplateSectionId" },
] as const;

function modelNames(schemaPath: string) {
  return [...readFileSync(schemaPath, "utf8").matchAll(/^model\s+(\w+)\s*\{/gm)].map((match) => match[1]);
}

function enumDefinitions(schemaPath: string) {
  const source = readFileSync(schemaPath, "utf8");
  const enums = new Map<string, string[]>();

  for (const match of source.matchAll(/^enum\s+(\w+)\s*\{([\s\S]*?)^}/gm)) {
    const values = match[2]
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("//"));
    enums.set(match[1], values);
  }

  return enums;
}

function enumFieldReferences(schemaPath: string, enumNames: Iterable<string>) {
  const source = readFileSync(schemaPath, "utf8");
  const enumNameSet = new Set(enumNames);
  const references = new Map<string, string[]>();

  for (const modelMatch of source.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^}/gm)) {
    const modelName = modelMatch[1];
    for (const line of modelMatch[2].split("\n")) {
      const fieldMatch = line.trim().match(/^(\w+)\s+(\w+)\b/);
      if (fieldMatch && enumNameSet.has(fieldMatch[2])) {
        const fields = references.get(fieldMatch[2]) ?? [];
        fields.push(`${modelName}.${fieldMatch[1]}`);
        references.set(fieldMatch[2], fields);
      }
    }
  }

  return references;
}

function modelBlock(schemaPath: string, model: string): string {
  const source = readFileSync(schemaPath, "utf8");
  const match = source.match(new RegExp(`^model\\s+${model}\\s*\\{([\\s\\S]*?)^}`, "m"));
  assert.ok(match, `${schemaPath} missing model ${model}`);
  return match[1];
}

function modelDirectives(schemaPath: string, model: string) {
  return modelBlock(schemaPath, model)
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("@@unique") || line.startsWith("@@index"));
}

function parseChecklistRows() {
  const doc = readFileSync(COMPATIBILITY_DOC, "utf8");
  const sharedModelsSection = doc.split("## Shared Models")[1]?.split("\n## ")[0] ?? "";
  const rows = new Map<string, string[]>();

  for (const line of sharedModelsSection.split("\n")) {
    if (!line.startsWith("| `")) {
      continue;
    }
    const cells = line
      .split("|")
      .slice(1, -1)
      .map((cell) => cell.trim());
    const model = cells[0]?.replace(/^`|`$/g, "");
    if (model) {
      rows.set(model, cells);
    }
  }

  return { doc, rows };
}

test("Prisma schema compatibility checklist covers every shared model", () => {
  const postgresModels = modelNames(POSTGRES_SCHEMA);
  const sqliteModels = modelNames(SQLITE_SCHEMA);
  const sharedModels = postgresModels.filter((model) => sqliteModels.includes(model)).sort();
  const { doc, rows } = parseChecklistRows();

  assert.match(
    doc,
    /\| model \| owner domain \| PostgreSQL schema \| SQLite schema \| compatibility status \| action \|/,
  );
  assert.equal(sharedModels.length, 54);
  assert.deepEqual(
    sharedModels.filter((model) => !rows.has(model)),
    [],
    "compatibility checklist must include every model shared by both Prisma schemas",
  );

  for (const model of sharedModels) {
    const row = rows.get(model);
    assert.ok(row, `${model} missing from compatibility checklist`);
    assert.equal(row[2], "`prisma/schema.prisma`", `${model} must point to PostgreSQL schema`);
    assert.equal(row[3], "`prisma/schema.sqlite.prisma`", `${model} must point to SQLite schema`);
    assert.match(row[4], /shared/i, `${model} must be marked as shared`);
    assert.match(row[5], /keep-compatible/i, `${model} must have a keep-compatible action`);
  }
});

test("Prisma schema compatibility checklist is generated and indexed", () => {
  const checklist = readFileSync(COMPATIBILITY_DOC, "utf8");
  const index = readFileSync("docs/index.md", "utf8");

  assert.match(checklist, /Generated by `scripts\/docs\/generate-prisma-schema-compatibility\.ts`/);
  assert.match(index, /docs\/prisma-schema-compatibility\.md/);
});

test("Prisma schema compatibility checklist documents PostgreSQL enum to SQLite string mappings", () => {
  const doc = readFileSync(COMPATIBILITY_DOC, "utf8");
  const postgresEnums = enumDefinitions(POSTGRES_SCHEMA);
  const enumReferences = enumFieldReferences(POSTGRES_SCHEMA, postgresEnums.keys());

  assert.match(doc, /## Provider Enum Mapping/);
  assert.equal(postgresEnums.size, 5);

  for (const [enumName, values] of postgresEnums) {
    assert.match(doc, new RegExp(`\\| \`${enumName}\` \\|`), `${enumName} missing from provider enum mapping`);

    for (const value of values) {
      assert.match(doc, new RegExp(`\`${value}\``), `${enumName} value ${value} missing from provider enum mapping`);
    }

    for (const fieldReference of enumReferences.get(enumName) ?? []) {
      assert.match(doc, new RegExp(`\`${fieldReference}\``), `${fieldReference} missing from provider enum mapping`);
      assert.match(
        doc,
        new RegExp(`\`${fieldReference}: String`),
        `${fieldReference} must document its SQLite String storage mapping`,
      );
    }
  }
});

test("Prisma schema compatibility checklist documents relation parent scopes and uniqueness", () => {
  const doc = readFileSync(COMPATIBILITY_DOC, "utf8");

  assert.match(doc, /## Relation Scope And Uniqueness/);

  for (const { model, parentScope } of RELATION_SCOPE_MODELS) {
    assert.match(doc, new RegExp(`\\| \`${model}\` \\|`), `${model} missing from relation scope table`);
    assert.match(doc, new RegExp(`\`${parentScope}\``), `${model} must document parent scope ${parentScope}`);

    for (const schemaPath of [POSTGRES_SCHEMA, SQLITE_SCHEMA]) {
      for (const directive of modelDirectives(schemaPath, model)) {
        assert.match(doc, new RegExp(`\`${directive.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\``));
      }
    }
  }
});
