export const SHOWCASE_PREVIEW_COMPONENT_NAMES = [
  "Button",
  "ButtonLink",
  "Checkbox",
  "Switch",
  "StatusBadge",
  "SegmentedControl",
  "DemoTabs",
  "Field",
  "FloatingSelect",
  "PageHeader",
  "WorkbenchSurface",
  "EditorBlock",
  "InspectorAside",
  "EmptyPage / EmptyRows",
  "UnitRowShell",
  "ProjectListItem",
  "ProjectSectionCard",
  "PresetLibraryItemRow",
  "TemplateSectionRow",
  "FolderBreadcrumb",
  "FolderRow",
  "MoveTargetPicker",
  "ModelFileRow",
  "SelectionBatchBar",
  "ToolbarCluster",
  "OperationStateStrip",
  "DemoFeedbackProvider",
  "SpecSection / SpecRow",
  "KSamplerCard",
  "DimensionsReadout",
  "ImageSizeControlGroup",
  "PresetBindingRow",
  "PromptBlockRow",
  "LoraRow / LoraColumn",
  "PresetMemberRow",
  "SortableRowShell",
  "AnchorRail",
  "HistoryDiffRow",
  "PresetCategorySidebar / PresetCategoryRow",
  "ImageThumbSmall / ImageListSmall",
  "ImageThumbMedium / ImageListMedium",
  "ImageGrid / ReviewImageBoard",
  "ImagePreviewFrame / ImagePreviewLarge",
  "QueueMetrics",
  "CurrentRunningProgressCard",
  "RunList / PendingReviewGroups",
  "ReviewMetaCard",
  "LogFilterBar / LogLine",
  "MonitorStatusRow",
  "ModelFileBrowser / ModelFileInspector",
  "LoginTokenPanel",
  "RouteHeaderSurface",
  "PageHeaderCard",
  "IconList",
  "CustomIconDemo",
  "IconMeaningTable",
] as const;

export type ShowcasePreviewComponentName = (typeof SHOWCASE_PREVIEW_COMPONENT_NAMES)[number];
