import {
  SHOWCASE_FAMILY_ROUTES,
  SHOWCASE_ROUTE_METADATA,
  type ShowcaseFamilyId,
  type ShowcaseRouteMetadata,
} from "../routing/showcase-routes";

export { SHOWCASE_FAMILY_ROUTES };
export type { ShowcaseFamilyId };

export type ShowcaseComponentStatus = "implemented" | "adapter" | "specialty";

export type ShowcaseFamily = ShowcaseRouteMetadata & {
  summary: string;
  intent: string;
};

export type ShowcaseComponentEntry = {
  familyId: ShowcaseFamilyId;
  reviewName: string;
  componentName: string;
  description: string;
  paths: string[];
  usedBy: string[];
  status: ShowcaseComponentStatus;
  exclusion?: string;
};

const SHOWCASE_FAMILY_DETAILS: Record<ShowcaseFamilyId, Pick<ShowcaseFamily, "summary" | "intent">> = {
  controls: {
    summary: "按钮、选择、切换、字段和状态徽标等最底层交互控件。",
    intent: "只审核控件本体的尺寸、状态、图标、可读性和响应式表现，不承载页面业务结构。",
  },
  surfaces: {
    summary: "页面标题、连续工作区、编辑区块、右侧详情栏、空状态和加载骨架。",
    intent: "审核工作台页面的结构层级和容器密度，避免卡片套卡片。",
  },
  "unit-items": {
    summary: "项目、小节、模板、预设、运行任务等可浏览、可选择、可操作的行项。",
    intent: "把跨页面重复的对象摘要行放在一起审，统一拖拽、勾选、主信息、元信息和行尾操作。",
  },
  folders: {
    summary: "项目、预设、模型和批量创建浏览器中的文件夹、路径、返回上级和移动目标。",
    intent: "统一所有文件夹浏览和移动目标选择模式，避免每个页面各写一套文件管理 UI。",
  },
  "batch-actions": {
    summary: "已选数量、全选、移动、删除、撤销、操作状态条、toast 和保存状态。",
    intent: "审核批量操作的危险级别、按钮密度、禁用态和反馈一致性。",
  },
  "generation-params": {
    summary: "画幅、尺寸、checkpoint、KSampler、batch、放大和小节参数。",
    intent: "把影响生成结果的参数控件从普通表单控件中拆出，集中审核可编辑密度和继承状态。",
  },
  "preset-prompt-lora": {
    summary: "预设绑定、导入、Prompt 块、编译预览、LoRA 两阶段和预设组成员。",
    intent: "集中审核资源来源、变体、级联、手动项和两阶段 LoRA 的表达方式。",
  },
  "taxonomy-history": {
    summary: "分类侧栏、分类编辑、槽位、排序规则、历史 diff、变体 rail 和小节 rail。",
    intent: "审核可拖拽排序、资源分类和历史差异的统一表达。",
  },
  images: {
    summary: "小图、中图、结果列表、审核面板、图片统计、Lightbox 和结果筛选。",
    intent: "统一所有生成图片的缩略图尺寸、选择态、状态 tag、批量操作和预览行为。",
  },
  runs: {
    summary: "队列指标、当前运行进度、运行/失败列表、待审核分组和执行参数摘要。",
    intent: "审核任务生命周期、分组、进度、错误和审核入口，不混入图片网格本体。",
  },
  system: {
    summary: "日志筛选、日志行、监控状态、探测结果、模型文件浏览和登录令牌。",
    intent: "集中审核偏系统工具的高密度信息行、终端式日志和文件详情结构。",
  },
  headers: {
    summary: "所有路由的固定顶部 header 展开、折叠和移动端合并状态。",
    intent: "作为专项保留，不混入普通容器族；专门审核页面身份和主操作归属。",
  },
  icons: {
    summary: "Lucide 图标、自定义 SVG 图标和图标语义说明。",
    intent: "作为素材专项保留，集中审核图标选择和产品语义。",
  },
};

export const SHOWCASE_FAMILIES = SHOWCASE_ROUTE_METADATA.map((family) => ({
  ...family,
  ...SHOWCASE_FAMILY_DETAILS[family.id],
})) satisfies readonly ShowcaseFamily[];

export const SHOWCASE_COMPONENTS: ShowcaseComponentEntry[] = [
  {
    familyId: "controls",
    reviewName: "通用按钮",
    componentName: "Button",
    description: "用于普通操作、主操作、危险操作、处理中、按下态和纯图标按钮。",
    paths: ["shared/primitives/button"],
    usedBy: ["所有页面工具栏", "行尾操作", "弹层确认"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "链接按钮",
    componentName: "ButtonLink",
    description: "用按钮外观进入其他 demo 路由，保持 Link 的客户端导航能力。",
    paths: ["shared/primitives/button"],
    usedBy: ["页面头操作", "列表行入口", "设置入口"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "选择勾选框",
    componentName: "Checkbox",
    description: "用于项目、预设、图片等列表里的单项选择和批量选择。",
    paths: ["shared/primitives/checkbox"],
    usedBy: ["项目列表", "预设库", "图片审核"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "开关控件",
    componentName: "Switch",
    description: "用于启用、禁用和设置类布尔选项。",
    paths: ["shared/primitives/switch"],
    usedBy: ["设置页", "小节启用状态", "SFW 模式"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "状态徽标",
    componentName: "StatusBadge",
    description: "用于运行中、待审、失败、已保存、草稿等短状态表达。",
    paths: ["shared/primitives/status-badge"],
    usedBy: ["任务", "项目", "预设", "系统监控"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "分段切换",
    componentName: "SegmentedControl",
    description: "用于视图模式、模型类型、托管/外部等互斥切换。",
    paths: ["shared/primitives/segmented-control"],
    usedBy: ["模型文件", "监控", "项目视图"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "标签切换",
    componentName: "DemoTabs",
    description: "用于任务 tab、结果筛选、日志筛选等带数量的标签切换。",
    paths: ["shared/primitives/demo-tabs"],
    usedBy: ["任务页", "结果页", "日志页"],
    status: "implemented",
  },
  {
    familyId: "controls",
    reviewName: "只读文本字段",
    componentName: "Field / TextAreaField",
    description: "用于显示名称、slug、路径、Prompt 和备注等字段内容。",
    paths: ["shared/primitives/field", "shared/primitives/text-area-field"],
    usedBy: ["预设详情", "模板编辑", "模型详情", "登录"],
    status: "implemented",
  },
  {
    familyId: "surfaces",
    reviewName: "页面标题栏",
    componentName: "PageHeader",
    description: "承载页面身份、返回、标题、副标题和主操作。",
    paths: ["shared/primitives/page-header"],
    usedBy: ["所有设计 demo 页面"],
    status: "implemented",
  },
  {
    familyId: "surfaces",
    reviewName: "连续工作区",
    componentName: "WorkbenchSurface",
    description: "用于项目、预设、模板和模型页面的主工作面，避免嵌套卡片。",
    paths: ["shared/patterns"],
    usedBy: ["项目详情", "预设库", "模型文件", "模板编辑"],
    status: "implemented",
  },
  {
    familyId: "surfaces",
    reviewName: "编辑区块",
    componentName: "EditorBlock",
    description: "统一编辑页里标题、说明、操作和内容的区块结构。",
    paths: ["shared/patterns"],
    usedBy: ["预设详情", "模板编辑", "分类编辑"],
    status: "implemented",
  },
  {
    familyId: "surfaces",
    reviewName: "右侧详情栏",
    componentName: "InspectorAside",
    description: "用于文件信息、保存状态、保护状态和探测结果等侧栏信息。",
    paths: ["shared/patterns"],
    usedBy: ["模型文件", "预设详情", "监控"],
    status: "implemented",
  },
  {
    familyId: "surfaces",
    reviewName: "空页面",
    componentName: "EmptyPage / EmptyRows",
    description: "用于整页无数据和局部列表无内容的空状态。",
    paths: ["shared/primitives/empty-page", "shared/primitives/empty-rows"],
    usedBy: ["缺失项目", "空文件夹", "空日志筛选"],
    status: "implemented",
  },
  {
    familyId: "unit-items",
    reviewName: "通用单元行壳",
    componentName: "UnitRowShell",
    description: "提供拖拽、勾选、媒体、主内容、元信息和行尾操作的槽位结构。",
    paths: ["shared/patterns"],
    usedBy: ["项目行", "预设条目", "模板小节", "运行任务"],
    status: "implemented",
  },
  {
    familyId: "unit-items",
    reviewName: "项目列表项",
    componentName: "ProjectListItem",
    description: "展示项目标题、状态、小节数、更新时间和最近图片预览。",
    paths: ["features/projects/project-list-item"],
    usedBy: ["项目列表页"],
    status: "adapter",
  },
  {
    familyId: "unit-items",
    reviewName: "项目小节项",
    componentName: "ProjectSectionCard",
    description: "展示项目详情中的小节名称、参数摘要、批量数量和最近图片。",
    paths: ["features/projects/project-section-card"],
    usedBy: ["项目详情页"],
    status: "adapter",
  },
  {
    familyId: "unit-items",
    reviewName: "预设库条目",
    componentName: "PresetLibraryItemRow",
    description: "展示预设或预设组名称、slug、描述、编号和进入箭头。",
    paths: ["features/presets/library-page"],
    usedBy: ["预设库"],
    status: "adapter",
  },
  {
    familyId: "unit-items",
    reviewName: "模板小节项",
    componentName: "TemplateSectionRow",
    description: "展示模板小节排序、参数摘要、编辑、复制和删除操作。",
    paths: ["features/templates/template-form-page"],
    usedBy: ["模板编辑页"],
    status: "adapter",
  },
  {
    familyId: "folders",
    reviewName: "通用路径面包屑",
    componentName: "FolderBreadcrumb",
    description: "统一项目、预设、模型和批量创建里的文件夹路径导航。",
    paths: ["shared/patterns"],
    usedBy: ["项目文件夹", "预设库", "模型浏览器", "批量创建"],
    status: "implemented",
    exclusion: "不归入批量操作，因为它只表达位置路径，不执行批量命令。",
  },
  {
    familyId: "folders",
    reviewName: "通用文件夹行",
    componentName: "FolderRow",
    description: "统一文件夹入口、条目数、排序手柄、编辑和删除操作。",
    paths: ["shared/patterns"],
    usedBy: ["项目文件夹行", "预设文件夹行", "模型文件夹行"],
    status: "implemented",
  },
  {
    familyId: "folders",
    reviewName: "移动目标选择器",
    componentName: "MoveTargetPicker",
    description: "统一菜单式和弹层式移动目标选择，支持层级缩进和当前目标禁用。",
    paths: ["shared/patterns"],
    usedBy: ["项目移动", "预设移动", "模型移动"],
    status: "implemented",
  },
  {
    familyId: "folders",
    reviewName: "模型文件行",
    componentName: "ModelFileRow",
    description: "展示模型文件或文件夹名称、大小、类型和更多操作。",
    paths: ["features/models/model-list"],
    usedBy: ["模型文件管理"],
    status: "adapter",
  },
  {
    familyId: "batch-actions",
    reviewName: "通用批量栏",
    componentName: "SelectionBatchBar",
    description: "统一已选数量、批量命令和清除选择的布局。",
    paths: ["shared/patterns"],
    usedBy: ["项目批量栏", "预设批量栏", "图片批量操作"],
    status: "implemented",
  },
  {
    familyId: "batch-actions",
    reviewName: "工具栏容器",
    componentName: "ToolbarCluster",
    description: "统一页面头、面板头、行尾操作的按钮间距、换行和对齐。",
    paths: ["shared/patterns"],
    usedBy: ["所有工具栏"],
    status: "implemented",
  },
  {
    familyId: "batch-actions",
    reviewName: "操作状态条",
    componentName: "OperationStateStrip",
    description: "横向展示保存队列、移动队列、错误数等操作状态。",
    paths: ["shared/feedback/operation-state-strip"],
    usedBy: ["预设库", "模板编辑", "登录"],
    status: "implemented",
  },
  {
    familyId: "batch-actions",
    reviewName: "Toast 反馈",
    componentName: "DemoFeedbackProvider",
    description: "为按钮点击提供成功、警告、错误和信息提示。",
    paths: ["shared/feedback/provider"],
    usedBy: ["所有 demo 按钮反馈"],
    status: "implemented",
  },
  {
    familyId: "generation-params",
    reviewName: "参数分组和参数行",
    componentName: "SpecSection / SpecRow",
    description: "用于采样、尺寸、checkpoint 等参数块的标题、说明和控件行。",
    paths: ["features/projects/editor/editor-controls"],
    usedBy: ["小节编辑器", "模板小节"],
    status: "implemented",
  },
  {
    familyId: "generation-params",
    reviewName: "KSampler 参数卡",
    componentName: "KSamplerCard",
    description: "展示 steps、cfg、denoise、sampler、scheduler 和 seed 策略。",
    paths: ["features/projects/editor/editor-controls"],
    usedBy: ["小节编辑器", "运行元信息"],
    status: "implemented",
  },
  {
    familyId: "generation-params",
    reviewName: "尺寸读数",
    componentName: "DimensionsReadout",
    description: "展示基础尺寸到最终尺寸的计算结果。",
    paths: ["features/projects/editor/editor-controls"],
    usedBy: ["小节编辑器", "批量创建"],
    status: "implemented",
  },
  {
    familyId: "generation-params",
    reviewName: "图片尺寸参数组",
    componentName: "ImageSizeControlGroup",
    description: "统一画幅、短边、放大倍数和尺寸读数。",
    paths: ["features/projects/editor/editor-controls"],
    usedBy: ["小节编辑器", "批量创建", "模板小节"],
    status: "implemented",
  },
  {
    familyId: "preset-prompt-lora",
    reviewName: "预设绑定行",
    componentName: "PresetBindingRow",
    description: "展示小节当前绑定的预设或预设组、分类、变体和资源数量。",
    paths: ["features/projects/editor/editor-presets"],
    usedBy: ["小节编辑器", "模板小节"],
    status: "implemented",
  },
  {
    familyId: "preset-prompt-lora",
    reviewName: "Prompt 块行",
    componentName: "PromptBlockRow",
    description: "展示正向或反向 Prompt 块、来源和展开内容。",
    paths: ["features/projects/editor/editor-prompts"],
    usedBy: ["小节编辑器", "预设详情"],
    status: "implemented",
  },
  {
    familyId: "preset-prompt-lora",
    reviewName: "LoRA 行和两阶段列",
    componentName: "LoraRow / LoraColumn",
    description: "展示 LoRA 文件、权重、启用、来源、触发词和 Stage 1/2 分列。",
    paths: ["features/projects/editor/editor-lora-history", "features/projects/editor/editor-lora-column"],
    usedBy: ["小节编辑器", "预设详情"],
    status: "implemented",
  },
  {
    familyId: "preset-prompt-lora",
    reviewName: "预设成员行",
    componentName: "PresetMemberRow",
    description: "统一预设组成员、批量导入候选和关联变体的选择行。",
    paths: ["features/presets/group-page"],
    usedBy: ["预设组", "批量创建", "预设详情"],
    status: "adapter",
  },
  {
    familyId: "taxonomy-history",
    reviewName: "可拖拽排序行",
    componentName: "SortableRowShell",
    description: "统一分类、变体、小节和成员排序的手柄、序号和内容槽位。",
    paths: ["shared/patterns"],
    usedBy: ["分类排序", "预设变体", "模板小节", "预设组成员"],
    status: "implemented",
  },
  {
    familyId: "taxonomy-history",
    reviewName: "侧向定位导航",
    componentName: "AnchorRail",
    description: "统一项目小节、模板小节和变体列表的页面内定位导航。",
    paths: ["shared/patterns"],
    usedBy: ["项目详情", "模板编辑", "预设详情"],
    status: "implemented",
  },
  {
    familyId: "taxonomy-history",
    reviewName: "历史差异行",
    componentName: "HistoryDiffRow",
    description: "展示参数、Prompt 和 LoRA 的 before/after 差异。",
    paths: ["features/projects/editor/editor-lora-history"],
    usedBy: ["小节编辑器", "预设详情", "预设组"],
    status: "implemented",
  },
  {
    familyId: "taxonomy-history",
    reviewName: "分类侧栏和分类行",
    componentName: "PresetCategorySidebar / PresetCategoryRow",
    description: "展示分类名称、slug、色块、条目数、编辑和删除保护。",
    paths: ["features/presets/library-page"],
    usedBy: ["预设库", "分类编辑"],
    status: "adapter",
  },
  {
    familyId: "images",
    reviewName: "小缩略图和小图列表",
    componentName: "ImageThumbSmall / ImageListSmall",
    description: "用于项目、小节和任务行里的密集结果预览。",
    paths: ["shared/media/image-thumb-small", "shared/media/image-list-small"],
    usedBy: ["项目列表", "小节卡片", "任务行"],
    status: "implemented",
  },
  {
    familyId: "images",
    reviewName: "中缩略图和中图列表",
    componentName: "ImageThumbMedium / ImageListMedium",
    description: "用于结果图、审核图、选择态、状态 tag 和快速操作槽。",
    paths: ["shared/media/image-thumb-medium", "shared/media/image-list-medium"],
    usedBy: ["审核页", "项目结果", "小节结果"],
    status: "implemented",
  },
  {
    familyId: "images",
    reviewName: "图片网格和审核面板",
    componentName: "ImageGrid / ReviewImageBoard",
    description: "统一结果网格、单次 run 审核、选择和批量操作入口。",
    paths: ["shared/media/image-grid", "shared/media/review-image-board"],
    usedBy: ["审核页", "项目结果页", "小节编辑器"],
    status: "implemented",
  },
  {
    familyId: "images",
    reviewName: "大图预览",
    componentName: "ImagePreviewFrame / ImagePreviewLarge",
    description: "提供 Lightbox 图片展示、缩放、拖拽、上一张和下一张。",
    paths: ["shared/media/image-preview-frame", "shared/media/image-preview-large"],
    usedBy: ["审核页", "项目结果页", "小节编辑器"],
    status: "implemented",
  },
  {
    familyId: "runs",
    reviewName: "队列指标",
    componentName: "QueueMetrics",
    description: "展示待审、运行中、失败等任务工作台指标。",
    paths: ["features/runs/queue-metrics"],
    usedBy: ["任务页"],
    status: "implemented",
  },
  {
    familyId: "runs",
    reviewName: "当前运行进度卡",
    componentName: "CurrentRunningProgressCard",
    description: "展示运行百分比、阶段、步数、耗时和剩余时间。",
    paths: ["features/runs/current-running-progress-card"],
    usedBy: ["任务页"],
    status: "implemented",
  },
  {
    familyId: "runs",
    reviewName: "运行任务列表",
    componentName: "RunList / PendingReviewGroups",
    description: "按项目分组展示运行、失败和待审核任务。",
    paths: ["features/runs/run-list", "features/runs/pending-review-groups"],
    usedBy: ["任务页"],
    status: "implemented",
  },
  {
    familyId: "runs",
    reviewName: "审核元信息卡",
    componentName: "ReviewMetaCard",
    description: "展示运行参数、Prompt、LoRA 和 KSampler 元信息。",
    paths: ["features/runs/review-meta-card"],
    usedBy: ["审核页"],
    status: "implemented",
  },
  {
    familyId: "system",
    reviewName: "日志筛选和日志行",
    componentName: "LogFilterBar / LogLine",
    description: "用于来源、级别、模块筛选和终端式日志行展示。",
    paths: ["features/settings/logs-page"],
    usedBy: ["日志页"],
    status: "adapter",
  },
  {
    familyId: "system",
    reviewName: "监控状态行",
    componentName: "MonitorStatusRow",
    description: "展示 Worker、ComfyUI API、任务积压等健康状态。",
    paths: ["features/settings/monitor-page"],
    usedBy: ["监控页"],
    status: "adapter",
  },
  {
    familyId: "system",
    reviewName: "模型文件浏览器",
    componentName: "ModelFileBrowser / ModelFileInspector",
    description: "展示模型类型切换、路径、搜索、文件列表和右侧文件详情。",
    paths: ["features/models/model-list"],
    usedBy: ["模型文件页"],
    status: "adapter",
    exclusion: "文件夹行复用 folders 族，文件详情和系统浏览器归入 system 族。",
  },
  {
    familyId: "system",
    reviewName: "登录令牌面板",
    componentName: "LoginTokenPanel",
    description: "展示本地 token 输入、登录/清除和验证状态。",
    paths: ["features/auth/login-page"],
    usedBy: ["登录页"],
    status: "adapter",
  },
  {
    familyId: "headers",
    reviewName: "固定顶栏设计稿",
    componentName: "RouteHeaderSurface",
    description: "展示页面 header 在桌面展开、桌面折叠和移动端合并三种状态。",
    paths: ["shell/header-surface", "routing/header-specs"],
    usedBy: ["所有设计 demo 路由"],
    status: "specialty",
  },
  {
    familyId: "headers",
    reviewName: "路由 Header 卡",
    componentName: "PageHeaderCard",
    description: "按路由列出页面身份、返回、状态和主操作的 header 预览。",
    paths: ["showcase/pages/headers-page", "routing/header-specs"],
    usedBy: ["Headers 专项"],
    status: "specialty",
  },
  {
    familyId: "icons",
    reviewName: "Lucide 图标列表",
    componentName: "IconList",
    description: "用于确认通用图标选择、尺寸和语义是否合适。",
    paths: ["showcase/icons/icon-list"],
    usedBy: ["Icons 专项"],
    status: "specialty",
  },
  {
    familyId: "icons",
    reviewName: "自定义 SVG 图标",
    componentName: "CustomIconDemo",
    description: "用于审核项目自定义 SVG 图标资产和渲染方式。",
    paths: ["showcase/icons/custom-icon-demo", "shared/primitives/icons/custom-svg"],
    usedBy: ["Icons 专项"],
    status: "specialty",
  },
  {
    familyId: "icons",
    reviewName: "图标语义表",
    componentName: "IconMeaningTable",
    description: "用中文解释图标在产品里的固定含义，减少图标误用。",
    paths: ["showcase/pages"],
    usedBy: ["Icons 专项", "组件拆分文档"],
    status: "specialty",
  },
];

export function getShowcaseFamily(id: ShowcaseFamilyId) {
  return SHOWCASE_FAMILIES.find((family) => family.id === id);
}

export function getShowcaseComponents(familyId: ShowcaseFamilyId) {
  return SHOWCASE_COMPONENTS.filter((component) => component.familyId === familyId);
}

export function getShowcaseFamilyIdByRoute(route: string): ShowcaseFamilyId | null {
  const normalized = route.startsWith("/") ? route : `/${route}`;
  return SHOWCASE_FAMILIES.find((family) => family.route === normalized)?.id ?? null;
}

export function isShowcaseFamilyId(value: string): value is ShowcaseFamilyId {
  return value in SHOWCASE_FAMILY_ROUTES;
}
