import { getCharacterLoraCandidateImage } from "@/server/repositories/character-lora-training";
import { updateCharacterLoraImageCaption, listCharacterLoraCandidateImages } from "@/server/services/character-lora-training/phase3-service";
import { getCharacterLoraTrainingJob } from "@/server/services/character-lora-training/job-service";
import {
  getManagedTrainingImageResultContext,
  getManagedTrainingProject,
  updateManagedTrainingImageResult,
} from "@/server/services/training/project-service";
import { getTrainingProject } from "@/server/services/training/read-service";
import { z } from "zod";

const singleCaptionRequestSchema = z.object({
  taskInput: z.union([
    z.string().trim().min(1),
    z.object({
      captionDraft: z.string().trim().min(1).optional(),
      prompt: z.string().trim().min(1).optional(),
    }).strict(),
  ]).optional(),
  captionDraft: z.string().trim().min(1).optional(),
}).strict();

const bulkCaptionRequestSchema = z.object({
  mode: z.enum(["kept_without_captions", "selected"]).optional(),
  imageResultIds: z.array(z.string().trim().min(1)).optional(),
  taskInput: z.union([
    z.string().trim().min(1),
    z.object({
      captionDraft: z.string().trim().min(1).optional(),
      prompt: z.string().trim().min(1).optional(),
    }).strict(),
  ]).optional(),
  captions: z.array(z.object({
    imageId: z.string().trim().min(1),
    captionDraft: z.string().trim().min(1),
  }).strict()).optional(),
}).strict();

type CaptionTaskSummary = {
  id: string;
  projectId: string;
  imageResultId: string;
  taskType: "caption_generation";
  generationKind: "text";
  status: "completed";
  outputText: string;
  createdAt: string;
};

export class TrainingCaptionServiceError extends Error {
  details?: unknown;
  status: number;

  constructor(message: string, status: number, details?: unknown) {
    super(message);
    this.name = "TrainingCaptionServiceError";
    this.status = status;
    this.details = details;
  }
}

function parseSingleCaptionRequest(input: unknown) {
  const result = singleCaptionRequestSchema.safeParse(input);
  if (result.success) return result.data;
  throw new TrainingCaptionServiceError("Invalid training image caption request", 400, {
    issues: result.error.issues.map((issue) => ({
      path: issue.path.join("."),
      message: issue.message,
    })),
  });
}

function parseBulkCaptionRequest(input: unknown) {
  const result = bulkCaptionRequestSchema.safeParse(input);
  if (result.success) return result.data;
  throw new TrainingCaptionServiceError("Invalid training bulk caption request", 400, {
    issues: result.error.issues.map((issue) => ({
      path: issue.path.join("."),
      message: issue.message,
    })),
  });
}

function resolveTaskCaptionDraft(input: { taskInput?: unknown; captionDraft?: string }) {
  if (typeof input.captionDraft === "string" && input.captionDraft.trim()) return input.captionDraft.trim();
  if (typeof input.taskInput === "string" && input.taskInput.trim()) return input.taskInput.trim();
  if (input.taskInput && typeof input.taskInput === "object" && !Array.isArray(input.taskInput)) {
    const payload = input.taskInput as Record<string, unknown>;
    if (typeof payload.captionDraft === "string" && payload.captionDraft.trim()) return payload.captionDraft.trim();
    if (typeof payload.prompt === "string" && payload.prompt.trim()) return payload.prompt.trim();
  }
  return null;
}

function captionMissing(value: string | null | undefined) {
  return !value || !value.trim() || value.trim() === "未填写说明文本";
}

function makeCaptionTask(projectId: string, imageResultId: string, outputText: string): CaptionTaskSummary {
  return {
    id: `training-caption-task-${imageResultId}-${Date.now()}`,
    projectId,
    imageResultId,
    taskType: "caption_generation",
    generationKind: "text",
    status: "completed",
    outputText,
    createdAt: new Date().toISOString(),
  };
}

function deriveManagedCaption(context: {
  sourceLabel: string;
  caption: string;
}, requestedCaption: string | null) {
  if (requestedCaption) return requestedCaption;
  if (!captionMissing(context.caption)) return context.caption;
  return `${context.sourceLabel}，训练说明`;
}

async function deriveProductionCaption(imageResultId: string, requestedCaption: string | null) {
  if (requestedCaption) return requestedCaption;
  const image = await getCharacterLoraCandidateImage(imageResultId);
  if (!image) {
    throw new TrainingCaptionServiceError("Training image result not found", 404, { imageResultId });
  }
  if (!captionMissing(image.captionDraft)) {
    return image.captionDraft!;
  }
  const job = await getCharacterLoraTrainingJob(image.jobId);
  return `${job.triggerToken}, candidate image, autogenerated caption`;
}

export async function generateTrainingImageCaption(imageResultId: string, input: unknown) {
  const parsed = parseSingleCaptionRequest(input);
  const requestedCaption = resolveTaskCaptionDraft(parsed);

  const managedContext = await getManagedTrainingImageResultContext(imageResultId);
  if (managedContext) {
    const caption = deriveManagedCaption({
      sourceLabel: managedContext.result.sourceLabel,
      caption: managedContext.result.caption,
    }, requestedCaption);
    const imageResult = await updateManagedTrainingImageResult(imageResultId, {
      captionDraft: caption,
    });
    if (!imageResult) {
      throw new TrainingCaptionServiceError("Training image result not found", 404, { imageResultId });
    }
    return {
      imageResult,
      task: makeCaptionTask(managedContext.project.id, imageResultId, caption),
    };
  }

  const caption = await deriveProductionCaption(imageResultId, requestedCaption);
  const updated = await updateCharacterLoraImageCaption(imageResultId, {
    captionDraft: caption,
  });
  const project = await getTrainingProject(updated.jobId);
  const imageResult = project.resultPool.find((result) => result.id === imageResultId);
  if (!imageResult) {
    throw new TrainingCaptionServiceError("Training image result not found after caption update", 404, {
      imageResultId,
      projectId: updated.jobId,
    });
  }
  return {
    imageResult,
    task: makeCaptionTask(updated.jobId, imageResultId, caption),
  };
}

export async function generateTrainingCaptions(projectId: string, input: unknown) {
  const parsed = parseBulkCaptionRequest(input);

  if (Array.isArray(parsed.captions)) {
    const images = await Promise.all(
      parsed.captions.map((caption) =>
        updateCharacterLoraImageCaption(caption.imageId, {
          captionDraft: caption.captionDraft,
        }),
      ),
    );
    return {
      projectId,
      images,
    };
  }

  const mode = parsed.mode;
  if (!mode) {
    throw new TrainingCaptionServiceError("mode is required", 400, {
      supportedModes: ["kept_without_captions", "selected"],
    });
  }

  const requestedCaption = resolveTaskCaptionDraft(parsed);
  const tasks: CaptionTaskSummary[] = [];

  const managedProject = await getManagedTrainingProject(projectId);
  if (managedProject) {
    const targetResults = mode === "selected"
      ? managedProject.resultPool.filter((result) => (parsed.imageResultIds ?? []).includes(result.id))
      : managedProject.resultPool.filter((result) => result.reviewStatus === "kept" && captionMissing(result.caption));

    if (mode === "selected" && (!parsed.imageResultIds || parsed.imageResultIds.length === 0)) {
      throw new TrainingCaptionServiceError("imageResultIds is required when mode=selected", 400);
    }

    for (const result of targetResults) {
      const caption = deriveManagedCaption({
        sourceLabel: result.sourceLabel,
        caption: result.caption,
      }, requestedCaption);
      await updateManagedTrainingImageResult(result.id, { captionDraft: caption });
      tasks.push(makeCaptionTask(projectId, result.id, caption));
    }

    return {
      projectId,
      mode,
      taskCount: tasks.length,
      tasks,
    };
  }

  if (mode === "selected" && (!parsed.imageResultIds || parsed.imageResultIds.length === 0)) {
    throw new TrainingCaptionServiceError("imageResultIds is required when mode=selected", 400);
  }

  const candidateImages = await listCharacterLoraCandidateImages(projectId, {});
  const targetImages = mode === "selected"
    ? candidateImages.filter((image) => (parsed.imageResultIds ?? []).includes(image.id))
    : candidateImages.filter((image) =>
      (image.reviewStatus === "keep" || image.reviewStatus === "included_in_training")
      && captionMissing(image.captionDraft),
    );

  for (const image of targetImages) {
    const caption = await deriveProductionCaption(image.id, requestedCaption);
    await updateCharacterLoraImageCaption(image.id, { captionDraft: caption });
    tasks.push(makeCaptionTask(projectId, image.id, caption));
  }

  return {
    projectId,
    mode,
    taskCount: tasks.length,
    tasks,
  };
}

export function mapTrainingCaptionError(error: unknown) {
  if (error instanceof TrainingCaptionServiceError) {
    return {
      message: error.message,
      status: error.status,
      details: error.details,
    };
  }

  return {
    message: "Unexpected training caption error",
    status: 500,
    details: error instanceof Error ? error.message : String(error),
  };
}
