import { ok } from "@/lib/api-response";

export const dynamic = "force-dynamic";

const WORKER_TASK_LEASE_TARGET_METADATA = {
  produces: ["workerTaskId", "workerTaskTargetType", "workerTaskTargetId"],
  responsePaths: {
    workerTaskId: "$.data.id",
    workerTaskTargetType: "$.data.targetType",
    workerTaskTargetId: "$.data.targetId",
  },
};

const WORKER_TASK_LEASE_HANDOFF_METADATA = {
  ...WORKER_TASK_LEASE_TARGET_METADATA,
  conditionalProduces: [
    {
      when: { workerTaskTargetType: "generationRun" },
      produces: ["generationTaskId"],
      responsePaths: { generationTaskId: "$.data.targetId" },
    },
    {
      when: { workerTaskTargetType: "trainingRun" },
      produces: ["trainingRunId"],
      responsePaths: { trainingRunId: "$.data.targetId" },
    },
  ],
};

const TRAINING_API_MANIFEST = {
  module: "training",
  version: 1,
  description: "HTTP capability manifest for the LoRA training workflow.",
  entrypoints: {
    projects: "/api/training/projects",
    runs: "/api/training/runs",
    models: "/api/training/models?kind=checkpoint",
    presets: "/api/training/presets",
    templates: "/api/training/templates",
    scheduler: "/api/training/scheduler/status",
  },
  workerSupervisor: {
    defaultCommand: "cmd /c npm run training:workers",
    mockCommand: "cmd /c npm run training:workers:mock",
    defaultWorkers: ["image", "dataset-freeze", "training"],
    script: "scripts/training/worker-queue.ts",
  },
  workflows: [
    {
      id: "project_setup",
      description: "Create a training project, upload reference images, and save profile data.",
      steps: [
        { method: "POST", path: "/api/training/projects" },
        { method: "POST", path: "/api/training/projects/:projectId/character-images" },
        { method: "GET", path: "/api/training/projects/:projectId/character-images" },
        { method: "GET", path: "/api/training/projects/:projectId/profile" },
        { method: "PATCH", path: "/api/training/projects/:projectId/profile" },
      ],
    },
    {
      id: "section_and_generation",
      description: "Manage sections, build generation inputs, preview, and run generation tasks.",
      steps: [
        { method: "GET", path: "/api/training/projects/:projectId/sections" },
        { method: "POST", path: "/api/training/projects/:projectId/sections" },
        { method: "PATCH", path: "/api/training/projects/:projectId/sections/:sectionId" },
        { method: "POST", path: "/api/training/sections/:sectionId/blocks" },
        { method: "PATCH", path: "/api/training/blocks/:blockId" },
        { method: "POST", path: "/api/training/projects/:projectId/generation-tasks" },
        { method: "PATCH", path: "/api/training/generation-tasks/:taskId" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/inputs" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/preview" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/run" },
      ],
    },
    {
      id: "result_review_and_dataset",
      description: "Review image results, update captions, and freeze a dataset revision.",
      steps: [
        { method: "GET", path: "/api/training/projects/:projectId/image-results" },
        { method: "POST", path: "/api/training/image-results/:imageResultId/review" },
        { method: "PATCH", path: "/api/training/image-results/:imageResultId" },
        { method: "POST", path: "/api/training/projects/:projectId/captions/generate" },
        { method: "GET", path: "/api/training/projects/:projectId/dataset-readiness" },
        { method: "POST", path: "/api/training/projects/:projectId/dataset-revisions" },
        { method: "GET", path: "/api/training/dataset-revisions/:revisionId" },
      ],
    },
    {
      id: "training_execution",
      description: "Launch training, poll status, manage cleanup, and create presets from completed runs.",
      steps: [
        { method: "POST", path: "/api/training/projects/:projectId/training-runs" },
        { method: "GET", path: "/api/training/training-runs/:trainingRunId" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/poll" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/cancel" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/cleanup" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/create-preset" },
      ],
    },
    {
      id: "worker_execution",
      description: "Lease worker tasks, heartbeat progress, and write worker progress or completion callbacks.",
      steps: [
        {
          id: "read_worker_status",
          description: "Inspect scheduler and worker queue health before leasing work.",
          method: "GET",
          path: "/api/training/worker/status",
        },
        {
          id: "lease_worker_task",
          description: "Lease the next queued worker task for a specific worker type.",
          method: "GET",
          path: "/api/training/worker/tasks/next",
          queryParamSchema: {
            requiredFields: ["workerType"],
            optionalFields: ["leaseOwner", "leaseDurationSeconds", "targetType", "targetId"],
            enumValues: {
              workerType: [
                "image_generation",
                "dataset_freeze",
                "training",
                "benchmark",
                "promotion",
                "prompt_card_draft",
              ],
            },
          },
          ...WORKER_TASK_LEASE_HANDOFF_METADATA,
        },
        {
          id: "heartbeat_worker_task",
          description: "Heartbeat a leased worker task and optionally extend the lease or report structured progress.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/heartbeat",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["leaseOwner", "leaseDurationSeconds", "progressJson"],
          },
        },
        {
          id: "complete_worker_task",
          description: "Mark a leased worker task complete after the domain-specific callback has persisted outputs.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/complete",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["leaseOwner", "output"],
          },
        },
        {
          id: "fail_worker_task",
          description: "Mark a leased worker task failed with a concise error summary and optional provider details.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/fail",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["errorSummary"],
            optionalFields: ["leaseOwner", "providerError"],
          },
        },
        { method: "GET", path: "/api/training/scheduler/status" },
        { method: "POST", path: "/api/training/scheduler/tick" },
        {
          id: "complete_generation_domain_task",
          description: "Persist generated outputs on the generation task before completing the leased worker task.",
          method: "POST",
          path: "/api/training/worker/generation-tasks/:taskId/complete",
          requires: ["generationTaskId"],
          pathParams: { taskId: "generationTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["resultImageResultId", "captionDraft", "reviewStatus"],
          },
          produces: ["outputId", "imageResultId"],
          responsePaths: {
            outputId: "$.data.outputResultIds[0]",
            imageResultId: "$.data.outputResultIds[0]",
          },
        },
        {
          id: "fail_generation_domain_task",
          description: "Persist a generation task failure before failing the leased worker task.",
          method: "POST",
          path: "/api/training/worker/generation-tasks/:taskId/fail",
          requires: ["generationTaskId"],
          pathParams: { taskId: "generationTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["errorSummary"],
          },
        },
        {
          id: "report_training_domain_progress",
          description: "Persist visible training progress on the training run while the worker is active.",
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/progress",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["currentStep", "targetSteps", "schedulerMessage"],
          },
        },
        {
          id: "complete_training_domain_run",
          description: "Persist the final LoRA artifact on the training run before completing the leased worker task.",
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/complete",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["artifactName"],
          },
          produces: ["finalLoraArtifactId"],
          responsePaths: { finalLoraArtifactId: "$.data.finalLoraArtifactId" },
        },
        {
          id: "fail_training_domain_run",
          description: "Persist a training run failure before failing the leased worker task.",
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/fail",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["errorSummary"],
          },
        },
      ],
    },
    {
      id: "agent_full_training_flow",
      description: "End-to-end HTTP-only path for agents to create a project, generate dataset images, train LoRA, and create a reusable preset.",
      steps: [
        {
          id: "create_project",
          description: "Create the managed training project and persist the returned project id.",
          method: "POST",
          path: "/api/training/projects",
          requestBody: {
            contentType: "application/json",
            requiredFields: ["title", "triggerToken", "templateId", "trainingTemplateId", "checkpointRelativePath"],
            optionalFields: ["characterName", "projectName", "usagePrompt", "detailPrompt", "selectedReferenceIds", "sections", "trainingDefaults"],
          },
          produces: ["projectId"],
          responsePaths: { projectId: "$.data.id" },
        },
        {
          id: "upload_reference_image",
          description: "Upload source/reference images for the project profile.",
          method: "POST",
          path: "/api/training/projects/:projectId/character-images",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentTypes: ["application/json", "multipart/form-data"],
            requiredOneOf: ["artifactId", "file"],
            optionalFields: ["role", "kind", "relativePath"],
          },
          produces: ["imageId"],
          responsePaths: { imageId: "$.data.id" },
        },
        {
          id: "save_profile",
          description: "Write the project profile prompts and metadata used by later generation tasks.",
          method: "PATCH",
          path: "/api/training/projects/:projectId/profile",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            requiredOneOf: ["loraUsagePrompt", "characterDetailPrompt", "profileSummary"],
          },
        },
        {
          id: "create_section",
          description: "Create or seed a training section that will own generation tasks.",
          method: "POST",
          path: "/api/training/projects/:projectId/sections",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["sourceSectionId"],
          },
          produces: ["sectionId"],
          responsePaths: { sectionId: "$.data.id" },
        },
        {
          id: "add_scene_block",
          description: "Attach a local or preset-backed scene block to the section.",
          method: "POST",
          path: "/api/training/sections/:sectionId/blocks",
          requires: ["projectId", "sectionId"],
          pathParams: { sectionId: "sectionId" },
          queryParamBindings: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["title", "text"],
            optionalFields: ["source", "sourceId", "variantId"],
          },
          produces: ["blockId"],
          responsePaths: { blockId: "$.data.id" },
        },
        {
          id: "create_generation_task",
          description: "Create a generation task draft for dataset/reference images.",
          method: "POST",
          path: "/api/training/projects/:projectId/generation-tasks",
          requires: ["projectId", "sectionId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["sectionId"],
            optionalFields: ["taskType", "supplementalPrompt"],
            bodyParams: { sectionId: "sectionId" },
          },
          produces: ["taskId"],
          responsePaths: { taskId: "$.data.id" },
        },
        {
          id: "attach_generation_inputs",
          description: "Attach reference inputs to the generation task draft.",
          method: "POST",
          path: "/api/training/generation-tasks/:taskId/inputs",
          requires: ["taskId", "imageId"],
          pathParams: { taskId: "taskId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["referenceId"],
            bodyParams: { referenceId: "imageId" },
          },
        },
        {
          id: "preview_generation_task",
          description: "Preview the final generation payload before queueing work.",
          method: "POST",
          path: "/api/training/generation-tasks/:taskId/preview",
          requires: ["taskId"],
          pathParams: { taskId: "taskId" },
          requestBody: { contentType: "none" },
          produces: ["preview"],
          responsePaths: { preview: "$.data" },
        },
        {
          id: "run_generation_task",
          description: "Queue the generation task for worker execution.",
          method: "POST",
          path: "/api/training/generation-tasks/:taskId/run",
          requires: ["taskId"],
          pathParams: { taskId: "taskId" },
          requestBody: { contentType: "none" },
          produces: ["queuedGenerationTaskId"],
          responsePaths: { queuedGenerationTaskId: "$.data.id" },
        },
        {
          id: "tick_generation_scheduler",
          description: "Advance the scheduler so queued generation work becomes leaseable.",
          method: "POST",
          path: "/api/training/scheduler/tick",
          requires: ["taskId"],
          requestBody: { contentType: "none" },
          produces: ["workerTaskQueued"],
          responsePaths: { workerTaskQueued: "$.data.id" },
        },
        {
          id: "lease_generation_worker_task",
          description: "Lease the next generation worker task and verify it matches the queued generation task.",
          method: "GET",
          path: "/api/training/worker/tasks/next",
          requires: ["workerTaskQueued", "taskId"],
          queryParams: {
            workerType: "image_generation",
            leaseOwner: "agent",
            targetType: "generationRun",
          },
          queryParamBindings: { targetId: "taskId" },
          ...WORKER_TASK_LEASE_TARGET_METADATA,
          expectedTarget: { type: "generationRun", idHandoff: "taskId" },
        },
        {
          id: "heartbeat_generation_worker_task",
          description: "Heartbeat the leased generation worker task while executing it.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/heartbeat",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["leaseOwner", "leaseDurationSeconds", "progressJson"],
          },
        },
        {
          id: "complete_generation_task",
          description: "Persist generation output data on the generation task.",
          method: "POST",
          path: "/api/training/worker/generation-tasks/:taskId/complete",
          requires: ["taskId"],
          pathParams: { taskId: "taskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["resultImageResultId", "captionDraft", "reviewStatus"],
          },
          produces: ["outputId", "imageResultId"],
          responsePaths: {
            outputId: "$.data.outputResultIds[0]",
            imageResultId: "$.data.outputResultIds[0]",
          },
        },
        {
          id: "complete_generation_worker_task",
          description: "Mark the leased worker task complete after generation outputs are persisted.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/complete",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["result", "summary", "artifactIds"],
          },
        },
        {
          id: "list_generation_outputs",
          description: "Read generated outputs mapped into project result candidates.",
          method: "GET",
          path: "/api/training/generation-tasks/:taskId/outputs",
          requires: ["taskId"],
          pathParams: { taskId: "taskId" },
          produces: ["outputId", "imageResultId"],
          responsePaths: {
            outputId: "$.data[0].id",
            imageResultId: "$.data[0].id",
          },
        },
        {
          id: "apply_output_to_reference",
          description: "Optionally apply a generated output back to the project reference image pool.",
          method: "POST",
          path: "/api/training/generation-outputs/:outputId/apply",
          requires: ["outputId"],
          pathParams: { outputId: "outputId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["targetEntityType"],
            optionalFields: ["targetEntityId", "targetField"],
          },
          produces: ["imageId"],
          responsePaths: { imageId: "$.data.result.id" },
        },
        {
          id: "review_image_result",
          description: "Keep or reject generated image results before freezing the dataset.",
          method: "POST",
          path: "/api/training/image-results/:imageResultId/review",
          requires: ["imageResultId"],
          pathParams: { imageResultId: "imageResultId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["reviewStatus"],
          },
        },
        {
          id: "generate_missing_captions",
          description: "Generate captions for kept images that still need training text.",
          method: "POST",
          path: "/api/training/projects/:projectId/captions/generate",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["mode", "imageResultIds"],
          },
        },
        {
          id: "read_dataset_readiness",
          description: "Check kept image counts, caption gaps, and active training blockers.",
          method: "GET",
          path: "/api/training/projects/:projectId/dataset-readiness",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
        },
        {
          id: "freeze_dataset_revision",
          description: "Create an immutable dataset revision from kept images and captions.",
          method: "POST",
          path: "/api/training/projects/:projectId/dataset-revisions",
          requires: ["projectId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["notes", "label"],
          },
          produces: ["revisionId"],
          responsePaths: { revisionId: "$.data.revision.id" },
        },
        {
          id: "create_training_run",
          description: "Queue LoRA training from the frozen dataset revision.",
          method: "POST",
          path: "/api/training/projects/:projectId/training-runs",
          requires: ["projectId", "revisionId"],
          pathParams: { projectId: "projectId" },
          requestBody: {
            contentType: "application/json",
            requiredFields: ["revisionId"],
            optionalFields: ["config"],
            bodyParams: { revisionId: "revisionId" },
          },
          produces: ["trainingRunId"],
          responsePaths: { trainingRunId: "$.data.id" },
        },
        {
          id: "tick_training_scheduler",
          description: "Advance the scheduler so queued training work becomes leaseable.",
          method: "POST",
          path: "/api/training/scheduler/tick",
          requires: ["trainingRunId"],
          requestBody: { contentType: "none" },
          produces: ["workerTaskQueued"],
          responsePaths: { workerTaskQueued: "$.data.id" },
        },
        {
          id: "lease_training_worker_task",
          description: "Lease the next training worker task and verify it matches the queued training run.",
          method: "GET",
          path: "/api/training/worker/tasks/next",
          requires: ["workerTaskQueued", "trainingRunId"],
          queryParams: {
            workerType: "training",
            leaseOwner: "agent",
            targetType: "trainingRun",
          },
          queryParamBindings: { targetId: "trainingRunId" },
          ...WORKER_TASK_LEASE_TARGET_METADATA,
          expectedTarget: { type: "trainingRun", idHandoff: "trainingRunId" },
        },
        {
          id: "heartbeat_training_worker_task",
          description: "Heartbeat the leased training worker task while the runner is active.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/heartbeat",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["leaseOwner", "leaseDurationSeconds", "progressJson"],
          },
        },
        {
          id: "report_training_progress",
          description: "Persist step progress and scheduler messages for the active training run.",
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/progress",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["currentStep", "targetSteps", "schedulerMessage"],
          },
        },
        {
          id: "complete_training_run",
          description: "Persist the final LoRA artifact from the completed training run.",
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/complete",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["artifactName"],
          },
          produces: ["finalLoraArtifactId"],
          responsePaths: { finalLoraArtifactId: "$.data.finalLoraArtifactId" },
        },
        {
          id: "complete_training_worker_task",
          description: "Mark the leased worker task complete after the training run is finalized.",
          method: "POST",
          path: "/api/training/worker/tasks/:taskId/complete",
          requires: ["workerTaskId"],
          pathParams: { taskId: "workerTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["result", "summary", "artifactIds"],
          },
        },
        {
          id: "poll_training_run",
          description: "Read the completed training run state before cleanup or preset creation.",
          method: "POST",
          path: "/api/training/training-runs/:trainingRunId/poll",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: { contentType: "none" },
        },
        {
          id: "cleanup_training_run",
          description: "Run idempotent cleanup for temporary training artifacts.",
          method: "POST",
          path: "/api/training/training-runs/:trainingRunId/cleanup",
          requires: ["trainingRunId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: { contentType: "none" },
        },
        {
          id: "create_preset_from_training_run",
          description: "Create a reusable training preset from the final LoRA artifact.",
          method: "POST",
          path: "/api/training/training-runs/:trainingRunId/create-preset",
          requires: ["trainingRunId", "finalLoraArtifactId"],
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["title", "presetName", "category", "categoryId", "folder"],
          },
          produces: ["presetId"],
          responsePaths: { presetId: "$.data.id" },
        },
      ],
    },
  ],
  resources: {
    projects: {
      list: { method: "GET", path: "/api/training/projects" },
      create: { method: "POST", path: "/api/training/projects" },
      detail: { method: "GET", path: "/api/training/projects/:projectId" },
      update: { method: "PATCH", path: "/api/training/projects/:projectId" },
      remove: { method: "DELETE", path: "/api/training/projects/:projectId" },
      reorder: { method: "POST", path: "/api/training/projects/reorder" },
      archive: { method: "POST", path: "/api/training/projects/:projectId/archive" },
      restore: { method: "POST", path: "/api/training/projects/:projectId/restore" },
      saveAsTemplate: { method: "POST", path: "/api/training/projects/:projectId/save-as-template" },
    },
    presets: {
      list: { method: "GET", path: "/api/training/presets" },
      create: { method: "POST", path: "/api/training/presets" },
      detail: { method: "GET", path: "/api/training/presets/:presetId" },
      update: { method: "PATCH", path: "/api/training/presets/:presetId" },
      remove: { method: "DELETE", path: "/api/training/presets/:presetId" },
      sortRules: { method: "POST", path: "/api/training/presets/sort-rules" },
    },
    templates: {
      list: { method: "GET", path: "/api/training/templates" },
      create: { method: "POST", path: "/api/training/templates" },
      detail: { method: "GET", path: "/api/training/templates/:templateId" },
      update: { method: "PATCH", path: "/api/training/templates/:templateId" },
      remove: { method: "DELETE", path: "/api/training/templates/:templateId" },
      reorder: { method: "POST", path: "/api/training/templates/reorder" },
      createProject: { method: "POST", path: "/api/training/templates/:templateId/projects" },
      sections: {
        list: { method: "GET", path: "/api/training/templates/:templateId/sections" },
        create: { method: "POST", path: "/api/training/templates/:templateId/sections" },
        reorder: { method: "POST", path: "/api/training/templates/:templateId/sections/reorder" },
        detail: { method: "GET", path: "/api/training/templates/:templateId/sections/:sectionId" },
        update: { method: "PATCH", path: "/api/training/templates/:templateId/sections/:sectionId" },
        remove: { method: "DELETE", path: "/api/training/templates/:templateId/sections/:sectionId" },
        blocks: {
          create: { method: "POST", path: "/api/training/templates/:templateId/sections/:sectionId/blocks" },
          reorder: { method: "POST", path: "/api/training/templates/:templateId/sections/:sectionId/blocks/reorder" },
        },
      },
      blocks: {
        update: { method: "PATCH", path: "/api/training/templates/:templateId/blocks/:blockId" },
        remove: { method: "DELETE", path: "/api/training/templates/:templateId/blocks/:blockId" },
      },
    },
    models: {
      checkpoints: { method: "GET", path: "/api/training/models?kind=checkpoint" },
      loras: { method: "GET", path: "/api/training/models?kind=lora" },
    },
    runs: {
      list: { method: "GET", path: "/api/training/runs" },
    },
    projectMedia: {
      characterImages: {
        list: { method: "GET", path: "/api/training/projects/:projectId/character-images" },
        create: { method: "POST", path: "/api/training/projects/:projectId/character-images" },
        update: { method: "PATCH", path: "/api/training/character-images/:imageId" },
        remove: { method: "DELETE", path: "/api/training/character-images/:imageId" },
        addToResults: { method: "POST", path: "/api/training/character-images/:imageId/add-to-results" },
      },
      imageResults: {
        list: { method: "GET", path: "/api/training/projects/:projectId/image-results" },
        upload: { method: "POST", path: "/api/training/projects/:projectId/image-results/upload" },
        caption: { method: "POST", path: "/api/training/image-results/:imageResultId/caption" },
        review: { method: "POST", path: "/api/training/image-results/:imageResultId/review" },
        update: { method: "PATCH", path: "/api/training/image-results/:imageResultId" },
        remove: { method: "DELETE", path: "/api/training/image-results/:imageResultId" },
      },
    },
    sections: {
      list: { method: "GET", path: "/api/training/projects/:projectId/sections" },
      create: { method: "POST", path: "/api/training/projects/:projectId/sections" },
      reorder: { method: "POST", path: "/api/training/projects/:projectId/sections/reorder" },
      projectDetail: { method: "GET", path: "/api/training/projects/:projectId/sections/:sectionId" },
      projectUpdate: { method: "PATCH", path: "/api/training/projects/:projectId/sections/:sectionId" },
      projectRemove: { method: "DELETE", path: "/api/training/projects/:projectId/sections/:sectionId" },
      detail: { method: "GET", path: "/api/training/sections/:sectionId" },
      update: { method: "PATCH", path: "/api/training/sections/:sectionId" },
      remove: { method: "DELETE", path: "/api/training/sections/:sectionId" },
      sceneDescription: { method: "GET", path: "/api/training/sections/:sectionId/scene-description" },
      runs: { method: "GET", path: "/api/training/sections/:sectionId/runs" },
      enqueueRun: { method: "POST", path: "/api/training/sections/:sectionId/runs" },
      blocks: {
        create: { method: "POST", path: "/api/training/sections/:sectionId/blocks" },
        reorder: { method: "POST", path: "/api/training/sections/:sectionId/blocks/reorder" },
        update: { method: "PATCH", path: "/api/training/blocks/:blockId" },
        remove: { method: "DELETE", path: "/api/training/blocks/:blockId" },
        detach: { method: "POST", path: "/api/training/blocks/:blockId/detach" },
      },
    },
    generationTasks: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/generation-tasks" },
      projectCreate: { method: "POST", path: "/api/training/projects/:projectId/generation-tasks" },
      detail: { method: "GET", path: "/api/training/generation-tasks/:taskId" },
      update: { method: "PATCH", path: "/api/training/generation-tasks/:taskId" },
      remove: { method: "DELETE", path: "/api/training/generation-tasks/:taskId" },
      cancel: { method: "POST", path: "/api/training/generation-tasks/:taskId/cancel" },
      inputs: { method: "POST", path: "/api/training/generation-tasks/:taskId/inputs" },
      removeInput: { method: "DELETE", path: "/api/training/generation-inputs/:inputId" },
      supplementalImages: { method: "POST", path: "/api/training/generation-tasks/:taskId/supplemental-images" },
      preview: { method: "POST", path: "/api/training/generation-tasks/:taskId/preview" },
      run: { method: "POST", path: "/api/training/generation-tasks/:taskId/run" },
      outputs: { method: "GET", path: "/api/training/generation-tasks/:taskId/outputs" },
      applyOutput: { method: "POST", path: "/api/training/generation-outputs/:outputId/apply" },
    },
    sectionRuns: {
      detail: { method: "GET", path: "/api/training/section-runs/:runId" },
      cancel: { method: "POST", path: "/api/training/section-runs/:runId/cancel" },
    },
    datasetRevisions: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/dataset-revisions" },
      create: { method: "POST", path: "/api/training/projects/:projectId/dataset-revisions" },
      detail: { method: "GET", path: "/api/training/dataset-revisions/:revisionId" },
    },
    trainingRuns: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/training-runs" },
      create: { method: "POST", path: "/api/training/projects/:projectId/training-runs" },
      detail: { method: "GET", path: "/api/training/training-runs/:trainingRunId" },
      remove: { method: "DELETE", path: "/api/training/training-runs/:trainingRunId" },
      poll: { method: "POST", path: "/api/training/training-runs/:trainingRunId/poll" },
      cancel: { method: "POST", path: "/api/training/training-runs/:trainingRunId/cancel" },
      cleanup: { method: "POST", path: "/api/training/training-runs/:trainingRunId/cleanup" },
      createPreset: { method: "POST", path: "/api/training/training-runs/:trainingRunId/create-preset" },
    },
    scheduler: {
      status: { method: "GET", path: "/api/training/scheduler/status" },
      tick: { method: "POST", path: "/api/training/scheduler/tick" },
    },
    worker: {
      generation: {
        complete: {
          method: "POST",
          path: "/api/training/worker/generation-tasks/:taskId/complete",
          pathParams: { taskId: "generationTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["resultImageResultId", "captionDraft", "reviewStatus"],
          },
          produces: ["outputId", "imageResultId"],
          responsePaths: {
            outputId: "$.data.outputResultIds[0]",
            imageResultId: "$.data.outputResultIds[0]",
          },
        },
        fail: {
          method: "POST",
          path: "/api/training/worker/generation-tasks/:taskId/fail",
          pathParams: { taskId: "generationTaskId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["errorSummary"],
          },
        },
      },
      training: {
        progress: {
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/progress",
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["currentStep", "targetSteps", "schedulerMessage"],
          },
        },
        complete: {
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/complete",
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["artifactName"],
          },
          produces: ["finalLoraArtifactId"],
          responsePaths: { finalLoraArtifactId: "$.data.finalLoraArtifactId" },
        },
        fail: {
          method: "POST",
          path: "/api/training/worker/training-runs/:trainingRunId/fail",
          pathParams: { trainingRunId: "trainingRunId" },
          requestBody: {
            contentType: "application/json",
            optionalFields: ["errorSummary"],
          },
        },
      },
    },
    workerTasks: {
      status: { method: "GET", path: "/api/training/worker/status" },
      next: {
        method: "GET",
        path: "/api/training/worker/tasks/next",
        queryParamSchema: {
          requiredFields: ["workerType"],
          optionalFields: ["leaseOwner", "leaseDurationSeconds", "targetType", "targetId"],
          enumValues: {
            workerType: [
              "image_generation",
              "dataset_freeze",
              "training",
              "benchmark",
              "promotion",
              "prompt_card_draft",
            ],
          },
        },
        ...WORKER_TASK_LEASE_HANDOFF_METADATA,
      },
      heartbeat: {
        method: "POST",
        path: "/api/training/worker/tasks/:taskId/heartbeat",
        pathParams: { taskId: "workerTaskId" },
        requestBody: {
          contentType: "application/json",
          optionalFields: ["leaseOwner", "leaseDurationSeconds", "progressJson"],
        },
      },
      complete: {
        method: "POST",
        path: "/api/training/worker/tasks/:taskId/complete",
        pathParams: { taskId: "workerTaskId" },
        requestBody: {
          contentType: "application/json",
          optionalFields: ["leaseOwner", "output"],
        },
      },
      fail: {
        method: "POST",
        path: "/api/training/worker/tasks/:taskId/fail",
        pathParams: { taskId: "workerTaskId" },
        requestBody: {
          contentType: "application/json",
          requiredFields: ["errorSummary"],
          optionalFields: ["leaseOwner", "providerError"],
        },
      },
    },
    taxonomy: {
      sceneCategories: { method: "GET", path: "/api/training/scene-description/categories" },
      createSceneCategory: { method: "POST", path: "/api/training/scene-description/categories" },
      updateSceneCategory: { method: "PATCH", path: "/api/training/scene-description/categories/:categoryId" },
      removeSceneCategory: { method: "DELETE", path: "/api/training/scene-description/categories/:categoryId" },
      sceneFolders: { method: "GET", path: "/api/training/scene-description/folders" },
      createSceneFolder: { method: "POST", path: "/api/training/scene-description/folders" },
      updateSceneFolder: { method: "PATCH", path: "/api/training/scene-description/folders/:folderId" },
      removeSceneFolder: { method: "DELETE", path: "/api/training/scene-description/folders/:folderId" },
      textRevisions: { method: "GET", path: "/api/training/projects/:projectId/text-revisions" },
      createTextRevision: { method: "POST", path: "/api/training/projects/:projectId/text-revisions" },
      restoreTextRevision: { method: "POST", path: "/api/training/text-revisions/:revisionId/restore" },
    },
    sceneDescriptionPresets: {
      list: { method: "GET", path: "/api/training/scene-description/presets" },
      create: { method: "POST", path: "/api/training/scene-description/presets" },
      detail: { method: "GET", path: "/api/training/scene-description/presets/:presetId" },
      update: { method: "PATCH", path: "/api/training/scene-description/presets/:presetId" },
      remove: { method: "DELETE", path: "/api/training/scene-description/presets/:presetId" },
      cascadeRemove: { method: "DELETE", path: "/api/training/scene-description/presets/:presetId/cascade" },
      usage: { method: "GET", path: "/api/training/scene-description/presets/:presetId/usage" },
    },
  },
} as const;

export async function GET() {
  return ok(TRAINING_API_MANIFEST);
}
