import { ok } from "@/lib/api-response";

export const dynamic = "force-dynamic";

const TRAINING_API_MANIFEST = {
  module: "training",
  version: 1,
  description: "HTTP capability manifest for the LoRA training workflow.",
  entrypoints: {
    projects: "/api/training/projects",
    runs: "/api/training/runs",
    models: "/api/training/models?kind=checkpoint",
    presets: "/api/training/presets",
    templates: "/api/training/templates",
    scheduler: "/api/training/scheduler/status",
  },
  workerSupervisor: {
    defaultCommand: "cmd /c npm run training:workers",
    mockCommand: "cmd /c npm run training:workers:mock",
    defaultWorkers: ["image", "dataset-freeze", "training"],
    script: "scripts/training/worker-queue.ts",
  },
  workflows: [
    {
      id: "project_setup",
      description: "Create a training project, upload reference images, and save profile data.",
      steps: [
        { method: "POST", path: "/api/training/projects" },
        { method: "POST", path: "/api/training/projects/:projectId/character-images" },
        { method: "GET", path: "/api/training/projects/:projectId/character-images" },
        { method: "GET", path: "/api/training/projects/:projectId/profile" },
        { method: "PATCH", path: "/api/training/projects/:projectId/profile" },
      ],
    },
    {
      id: "section_and_generation",
      description: "Manage sections, build generation inputs, preview, and run generation tasks.",
      steps: [
        { method: "GET", path: "/api/training/projects/:projectId/sections" },
        { method: "POST", path: "/api/training/projects/:projectId/sections" },
        { method: "PATCH", path: "/api/training/projects/:projectId/sections/:sectionId" },
        { method: "POST", path: "/api/training/sections/:sectionId/blocks" },
        { method: "PATCH", path: "/api/training/blocks/:blockId" },
        { method: "POST", path: "/api/training/projects/:projectId/generation-tasks" },
        { method: "PATCH", path: "/api/training/generation-tasks/:taskId" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/inputs" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/preview" },
        { method: "POST", path: "/api/training/generation-tasks/:taskId/run" },
      ],
    },
    {
      id: "result_review_and_dataset",
      description: "Review image results, update captions, and freeze a dataset revision.",
      steps: [
        { method: "GET", path: "/api/training/projects/:projectId/image-results" },
        { method: "POST", path: "/api/training/image-results/:imageResultId/review" },
        { method: "PATCH", path: "/api/training/image-results/:imageResultId" },
        { method: "POST", path: "/api/training/projects/:projectId/captions/generate" },
        { method: "GET", path: "/api/training/projects/:projectId/dataset-readiness" },
        { method: "POST", path: "/api/training/projects/:projectId/dataset-revisions" },
        { method: "GET", path: "/api/training/dataset-revisions/:revisionId" },
      ],
    },
    {
      id: "training_execution",
      description: "Launch training, poll status, manage cleanup, and create presets from completed runs.",
      steps: [
        { method: "POST", path: "/api/training/projects/:projectId/training-runs" },
        { method: "GET", path: "/api/training/training-runs/:trainingRunId" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/poll" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/cancel" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/cleanup" },
        { method: "POST", path: "/api/training/training-runs/:trainingRunId/create-preset" },
      ],
    },
    {
      id: "worker_execution",
      description: "Advance queued generation and training work, then write worker progress or completion callbacks.",
      steps: [
        { method: "GET", path: "/api/training/scheduler/status" },
        { method: "POST", path: "/api/training/scheduler/tick" },
        { method: "POST", path: "/api/training/worker/generation-tasks/:taskId/complete" },
        { method: "POST", path: "/api/training/worker/generation-tasks/:taskId/fail" },
        { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/progress" },
        { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/complete" },
        { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/fail" },
      ],
    },
  ],
  resources: {
    projects: {
      list: { method: "GET", path: "/api/training/projects" },
      create: { method: "POST", path: "/api/training/projects" },
      detail: { method: "GET", path: "/api/training/projects/:projectId" },
      update: { method: "PATCH", path: "/api/training/projects/:projectId" },
      remove: { method: "DELETE", path: "/api/training/projects/:projectId" },
      reorder: { method: "POST", path: "/api/training/projects/reorder" },
      archive: { method: "POST", path: "/api/training/projects/:projectId/archive" },
      restore: { method: "POST", path: "/api/training/projects/:projectId/restore" },
      saveAsTemplate: { method: "POST", path: "/api/training/projects/:projectId/save-as-template" },
    },
    presets: {
      list: { method: "GET", path: "/api/training/presets" },
      create: { method: "POST", path: "/api/training/presets" },
      detail: { method: "GET", path: "/api/training/presets/:presetId" },
      update: { method: "PATCH", path: "/api/training/presets/:presetId" },
      remove: { method: "DELETE", path: "/api/training/presets/:presetId" },
      sortRules: { method: "POST", path: "/api/training/presets/sort-rules" },
    },
    templates: {
      list: { method: "GET", path: "/api/training/templates" },
      create: { method: "POST", path: "/api/training/templates" },
      detail: { method: "GET", path: "/api/training/templates/:templateId" },
      update: { method: "PATCH", path: "/api/training/templates/:templateId" },
      remove: { method: "DELETE", path: "/api/training/templates/:templateId" },
      reorder: { method: "POST", path: "/api/training/templates/reorder" },
      createProject: { method: "POST", path: "/api/training/templates/:templateId/projects" },
      sections: {
        list: { method: "GET", path: "/api/training/templates/:templateId/sections" },
        create: { method: "POST", path: "/api/training/templates/:templateId/sections" },
        reorder: { method: "POST", path: "/api/training/templates/:templateId/sections/reorder" },
        detail: { method: "GET", path: "/api/training/templates/:templateId/sections/:sectionId" },
        update: { method: "PATCH", path: "/api/training/templates/:templateId/sections/:sectionId" },
        remove: { method: "DELETE", path: "/api/training/templates/:templateId/sections/:sectionId" },
        blocks: {
          create: { method: "POST", path: "/api/training/templates/:templateId/sections/:sectionId/blocks" },
          reorder: { method: "POST", path: "/api/training/templates/:templateId/sections/:sectionId/blocks/reorder" },
        },
      },
      blocks: {
        update: { method: "PATCH", path: "/api/training/templates/:templateId/blocks/:blockId" },
        remove: { method: "DELETE", path: "/api/training/templates/:templateId/blocks/:blockId" },
      },
    },
    models: {
      checkpoints: { method: "GET", path: "/api/training/models?kind=checkpoint" },
      loras: { method: "GET", path: "/api/training/models?kind=lora" },
    },
    runs: {
      list: { method: "GET", path: "/api/training/runs" },
    },
    projectMedia: {
      characterImages: {
        list: { method: "GET", path: "/api/training/projects/:projectId/character-images" },
        create: { method: "POST", path: "/api/training/projects/:projectId/character-images" },
        update: { method: "PATCH", path: "/api/training/character-images/:imageId" },
        remove: { method: "DELETE", path: "/api/training/character-images/:imageId" },
        addToResults: { method: "POST", path: "/api/training/character-images/:imageId/add-to-results" },
      },
      imageResults: {
        list: { method: "GET", path: "/api/training/projects/:projectId/image-results" },
        upload: { method: "POST", path: "/api/training/projects/:projectId/image-results/upload" },
        caption: { method: "POST", path: "/api/training/image-results/:imageResultId/caption" },
        review: { method: "POST", path: "/api/training/image-results/:imageResultId/review" },
        update: { method: "PATCH", path: "/api/training/image-results/:imageResultId" },
        remove: { method: "DELETE", path: "/api/training/image-results/:imageResultId" },
      },
    },
    sections: {
      list: { method: "GET", path: "/api/training/projects/:projectId/sections" },
      create: { method: "POST", path: "/api/training/projects/:projectId/sections" },
      reorder: { method: "POST", path: "/api/training/projects/:projectId/sections/reorder" },
      projectDetail: { method: "GET", path: "/api/training/projects/:projectId/sections/:sectionId" },
      projectUpdate: { method: "PATCH", path: "/api/training/projects/:projectId/sections/:sectionId" },
      projectRemove: { method: "DELETE", path: "/api/training/projects/:projectId/sections/:sectionId" },
      detail: { method: "GET", path: "/api/training/sections/:sectionId" },
      update: { method: "PATCH", path: "/api/training/sections/:sectionId" },
      remove: { method: "DELETE", path: "/api/training/sections/:sectionId" },
      sceneDescription: { method: "GET", path: "/api/training/sections/:sectionId/scene-description" },
      runs: { method: "GET", path: "/api/training/sections/:sectionId/runs" },
      enqueueRun: { method: "POST", path: "/api/training/sections/:sectionId/runs" },
      blocks: {
        create: { method: "POST", path: "/api/training/sections/:sectionId/blocks" },
        reorder: { method: "POST", path: "/api/training/sections/:sectionId/blocks/reorder" },
        update: { method: "PATCH", path: "/api/training/blocks/:blockId" },
        remove: { method: "DELETE", path: "/api/training/blocks/:blockId" },
        detach: { method: "POST", path: "/api/training/blocks/:blockId/detach" },
      },
    },
    generationTasks: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/generation-tasks" },
      projectCreate: { method: "POST", path: "/api/training/projects/:projectId/generation-tasks" },
      detail: { method: "GET", path: "/api/training/generation-tasks/:taskId" },
      update: { method: "PATCH", path: "/api/training/generation-tasks/:taskId" },
      remove: { method: "DELETE", path: "/api/training/generation-tasks/:taskId" },
      cancel: { method: "POST", path: "/api/training/generation-tasks/:taskId/cancel" },
      inputs: { method: "POST", path: "/api/training/generation-tasks/:taskId/inputs" },
      removeInput: { method: "DELETE", path: "/api/training/generation-inputs/:inputId" },
      supplementalImages: { method: "POST", path: "/api/training/generation-tasks/:taskId/supplemental-images" },
      preview: { method: "POST", path: "/api/training/generation-tasks/:taskId/preview" },
      run: { method: "POST", path: "/api/training/generation-tasks/:taskId/run" },
      outputs: { method: "GET", path: "/api/training/generation-tasks/:taskId/outputs" },
      applyOutput: { method: "POST", path: "/api/training/generation-outputs/:outputId/apply" },
    },
    sectionRuns: {
      detail: { method: "GET", path: "/api/training/section-runs/:runId" },
      cancel: { method: "POST", path: "/api/training/section-runs/:runId/cancel" },
    },
    datasetRevisions: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/dataset-revisions" },
      create: { method: "POST", path: "/api/training/projects/:projectId/dataset-revisions" },
      detail: { method: "GET", path: "/api/training/dataset-revisions/:revisionId" },
    },
    trainingRuns: {
      projectList: { method: "GET", path: "/api/training/projects/:projectId/training-runs" },
      create: { method: "POST", path: "/api/training/projects/:projectId/training-runs" },
      detail: { method: "GET", path: "/api/training/training-runs/:trainingRunId" },
      remove: { method: "DELETE", path: "/api/training/training-runs/:trainingRunId" },
      poll: { method: "POST", path: "/api/training/training-runs/:trainingRunId/poll" },
      cancel: { method: "POST", path: "/api/training/training-runs/:trainingRunId/cancel" },
      cleanup: { method: "POST", path: "/api/training/training-runs/:trainingRunId/cleanup" },
      createPreset: { method: "POST", path: "/api/training/training-runs/:trainingRunId/create-preset" },
    },
    scheduler: {
      status: { method: "GET", path: "/api/training/scheduler/status" },
      tick: { method: "POST", path: "/api/training/scheduler/tick" },
    },
    worker: {
      generation: {
        complete: { method: "POST", path: "/api/training/worker/generation-tasks/:taskId/complete" },
        fail: { method: "POST", path: "/api/training/worker/generation-tasks/:taskId/fail" },
      },
      training: {
        progress: { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/progress" },
        complete: { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/complete" },
        fail: { method: "POST", path: "/api/training/worker/training-runs/:trainingRunId/fail" },
      },
    },
    workerTasks: {
      status: { method: "GET", path: "/api/training/worker/status" },
      next: { method: "GET", path: "/api/training/worker/tasks/next" },
      heartbeat: { method: "POST", path: "/api/training/worker/tasks/:taskId/heartbeat" },
      complete: { method: "POST", path: "/api/training/worker/tasks/:taskId/complete" },
      fail: { method: "POST", path: "/api/training/worker/tasks/:taskId/fail" },
    },
    taxonomy: {
      sceneCategories: { method: "GET", path: "/api/training/scene-description/categories" },
      createSceneCategory: { method: "POST", path: "/api/training/scene-description/categories" },
      updateSceneCategory: { method: "PATCH", path: "/api/training/scene-description/categories/:categoryId" },
      removeSceneCategory: { method: "DELETE", path: "/api/training/scene-description/categories/:categoryId" },
      sceneFolders: { method: "GET", path: "/api/training/scene-description/folders" },
      createSceneFolder: { method: "POST", path: "/api/training/scene-description/folders" },
      updateSceneFolder: { method: "PATCH", path: "/api/training/scene-description/folders/:folderId" },
      removeSceneFolder: { method: "DELETE", path: "/api/training/scene-description/folders/:folderId" },
      textRevisions: { method: "GET", path: "/api/training/projects/:projectId/text-revisions" },
      createTextRevision: { method: "POST", path: "/api/training/projects/:projectId/text-revisions" },
      restoreTextRevision: { method: "POST", path: "/api/training/text-revisions/:revisionId/restore" },
    },
    sceneDescriptionPresets: {
      list: { method: "GET", path: "/api/training/scene-description/presets" },
      create: { method: "POST", path: "/api/training/scene-description/presets" },
      detail: { method: "GET", path: "/api/training/scene-description/presets/:presetId" },
      update: { method: "PATCH", path: "/api/training/scene-description/presets/:presetId" },
      remove: { method: "DELETE", path: "/api/training/scene-description/presets/:presetId" },
      cascadeRemove: { method: "DELETE", path: "/api/training/scene-description/presets/:presetId/cascade" },
      usage: { method: "GET", path: "/api/training/scene-description/presets/:presetId/usage" },
    },
  },
} as const;

export async function GET() {
  return ok(TRAINING_API_MANIFEST);
}
