import {icon,button,badge,progress,escapeHtml as esc,states} from './ui.js';
import {initialTasks} from './data.js';
const tasks = structuredClone(initialTasks);
let mode=location.hash==='#training'?'training':'generation', query='',project='',status='',kind='',period='',order='time',selected=new Set(),detailId=null;
const app=document.querySelector('#app'),detail=document.querySelector('#detail'),confirmDialog=document.querySelector('#confirm');
let returnFocus=null,toastTimer;
document.body.dataset.theme=localStorage.getItem('task-workspace-theme') || (matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');
const activeStates=['running','queued','submitted'];
const isTerminal=t=>['done','failed','cancelled'].includes(t.status);
const taskLabel=t=>t.kind==='lora'?'LoRA 训练':t.kind==='material'?'素材生成':'图片生产';
const statusBadge=t=>t.mode==='training'&&t.status==='queued'?'<span class="badge queued"><span class="status-dot" aria-hidden="true"></span>等待中</span>':badge(t.status);
const unit=t=>t.kind==='lora'?'步':'张';
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500);}
function matching(t){return t.mode===mode&&(!project||t.project===project)&&(!query||`${t.name} ${t.project} ${t.id} ${t.section}`.toLowerCase().includes(query.toLowerCase()))&&(!kind||t.kind===kind)&&(!period||Number(t.time.split(':')[0])>=14);}
function taskTitle(t){return `<button class="task-link" data-detail="${t.id}">${esc(t.name)}${icon('chevron')}</button>`;}
function actions(t){const id=`data-id="${t.id}"`;if(t.status==='running')return (t.mode==='generation'?button('暂停','pause','pause','',id):'')+button('取消','cancel','close','subtle',id);if(['submitted','queued'].includes(t.status))return button('取消','cancel','close','subtle small',id);if(t.status==='paused')return button('恢复','resume','play','small',id);if(t.status==='failed'||t.status==='cancelled')return button(t.kind==='material'?'补缺重试':t.kind==='lora'?'重新训练':'重试','retry','retry','small',id);return '';}
function currentRegion(){const t=tasks.find(t=>t.status==='running');if(!t)return `<section class="panel current-task"><div class="current-main"><div>${icon('check')}<h2>当前无任务执行</h2></div><p class="muted">等待队列中的任务将在执行资源可用后开始。</p></div></section>`;
 return `<section class="panel current-task" aria-label="当前执行"><div class="section-heading"><h2>当前执行</h2>${statusBadge(t)}</div><div class="current-main"><div><div class="task-title">${taskTitle(t)}</div><div class="task-meta"><span>${taskLabel(t)}</span><span>${esc(t.project)} / ${esc(t.section)}</span><span class="mono">${t.id}</span></div></div><div class="current-actions">${actions(t)}</div></div><div class="current-footer"><div class="current-progress">${progress(t.progress,t.stage)}</div><div class="execution-number"><span class="muted">已生成</span><strong class="mono">${t.output}<span class="muted"> / ${t.count}</span></strong></div><div class="execution-number"><span class="muted">已用时</span><strong class="mono">${t.duration}</strong></div></div></section>`;
}
function queueRegion(){const queue=tasks.filter(t=>matching(t)&&['queued','submitted'].includes(t.status));return `<section class="panel"><div class="section-heading"><h2>等待队列 <span class="muted">${queue.length}</span></h2></div>${queue.length?`<div class="queue-list">${queue.map((t,i)=>`<div class="queue-row"><span class="queue-order mono">${String(i+1).padStart(2,'0')}</span><div class="queue-info">${taskTitle(t)}<div class="task-meta"><span>${esc(t.project)}</span><span>${t.count} ${unit(t)}</span><span>${t.status==='submitted'?'已送入 ComfyUI 队列':t.kind==='lora'?'等待图片任务释放执行资源':'等待执行资源'}</span></div></div>${statusBadge(t)}<div class="queue-actions">${actions(t)}</div></div>`).join('')}</div>`:'<div class="empty-state compact">没有等待中的任务</div>'}</section>`;}
function historyRegion(){let rows=tasks.filter(t=>matching(t)&&!activeStates.includes(t.status)&&(!status||t.status===status));if(order==='project')rows.sort((a,b)=>a.project.localeCompare(b.project,'zh-CN'));return `<section class="panel history-panel"><div class="section-heading"><h2>任务记录 <span class="muted">${rows.length}</span></h2><div class="filters"><select id="status" aria-label="记录状态"><option value="">全部状态</option>${['done','failed',...(mode==='generation'?['paused']:[]),'cancelled'].map(s=>`<option value="${s}" ${status===s?'selected':''}>${states[s]}</option>`).join('')}</select><select id="order" aria-label="记录排序"><option value="time">时间倒序</option><option value="project" ${order==='project'?'selected':''}>按项目排列</option></select></div></div>${selected.size?`<div class="selection-bar"><span>已选择 ${selected.size} 项</span>${button('取消选择','clear-selection',null,'subtle small')}${button('删除所选','delete-selected','trash','danger small')}</div>`:''}${rows.length?`<div class="history-table"><table><thead><tr>${mode==='generation'?'<th class="selection-col"><input type="checkbox" id="select-all" aria-label="选择当前可删除任务" '+(rows.filter(isTerminal).every(t=>selected.has(t.id))?'checked':'')+'></th>':''}<th>任务</th><th>状态</th><th class="secondary-col">${mode==='generation'?'生成结果':'类型'}</th><th class="secondary-col">耗时</th><th class="secondary-col">创建时间</th><th class="action-col"><span class="sr-only">操作</span></th></tr></thead><tbody>${rows.map(t=>`<tr>${mode==='generation'?`<td class="selection-col"><input type="checkbox" data-select="${t.id}" aria-label="选择 ${esc(t.name)}" ${selected.has(t.id)?'checked':''} ${!isTerminal(t)?'disabled':''}></td>`:''}<td><div class="row-title">${taskTitle(t)}</div><div class="row-subtitle">${esc(t.project)} <span class="mono">${t.id}</span></div></td><td>${statusBadge(t)}</td><td class="secondary-col">${mode==='generation'?`<span class="mono">${t.output} / ${t.count}</span> 张`:taskLabel(t)}</td><td class="secondary-col mono">${t.duration}</td><td class="secondary-col mono">今天 ${t.time}</td><td class="action-col">${actions(t)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state">${icon('search')}<h3>没有匹配的任务</h3><p class="muted">试试其他名称，或清除筛选条件。</p>${button('清除筛选','reset',null,'subtle')}</div>`}</section>`;}
function content(){return currentRegion()+`<div class="toolbar"><label class="search-field">${icon('search')}<input id="search" type="search" placeholder="搜索任务名称或编号" aria-label="搜索任务名称或编号" value="${esc(query)}"></label><div class="filters"><select id="project" aria-label="项目筛选"><option value="">全部项目</option>${[...new Set(tasks.filter(t=>t.mode===mode).map(t=>t.project))].map(p=>`<option ${project===p?'selected':''}>${esc(p)}</option>`).join('')}</select>${mode==='training'?`<select id="kind" aria-label="任务类型"><option value="">全部类型</option><option value="material" ${kind==='material'?'selected':''}>素材生成</option><option value="lora" ${kind==='lora'?'selected':''}>LoRA 训练</option></select>`:''}<select id="period" aria-label="创建时间"><option value="">今天</option><option value="recent" ${period?'selected':''}>14:00 以后</option></select></div></div>${queueRegion()}${historyRegion()}`;}
function render(){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">${icon('layers')}</span><span>ComfyUI <strong>Manager</strong></span></div><nav aria-label="任务模块"><a href="#generation" class="nav-item ${mode==='generation'?'active':''}" ${mode==='generation'?'aria-current="page"':''}>${icon('tasks')}<span>生产任务</span></a><a href="#training" class="nav-item ${mode==='training'?'active':''}" ${mode==='training'?'aria-current="page"':''}>${icon('flask')}<span>训练任务</span></a></nav><div class="sidebar-bottom">${button(document.body.dataset.theme==='dark'?'浅色外观':'深色外观','theme',document.body.dataset.theme==='dark'?'sun':'moon','subtle')}</div></aside><main><header class="topbar"><h1>${mode==='generation'?'生产任务':'训练任务'}</h1><div class="topbar-right"><span class="connection"><span class="status-dot"></span>ComfyUI 已连接</span><button class="button icon-only mobile-theme" data-action="theme" aria-label="切换外观">${icon('sun')}</button></div></header><div class="workspace" id="content">${content()}</div></main><nav class="bottom-nav" aria-label="任务模块"><a href="#generation" class="nav-item ${mode==='generation'?'active':''}">${icon('tasks')}生产任务</a><a href="#training" class="nav-item ${mode==='training'?'active':''}">${icon('flask')}训练任务</a></nav></div>`;}
function updateContent(){document.querySelector('#content').innerHTML=content();}
function openDetail(id){const t=tasks.find(x=>x.id===id);if(!t)return;detailId=id;if(!detail.open)returnFocus=document.activeElement;detail.innerHTML=`<div class="dialog-header"><div><div class="task-meta"><span class="mono">${t.id}</span><span>${taskLabel(t)}</span></div><h2 id="detail-title">${esc(t.name)}</h2><div class="task-meta">${esc(t.project)} / ${esc(t.section)}</div></div><button class="button icon-only subtle" data-action="close-detail" aria-label="关闭任务详情">${icon('close')}</button></div><div class="dialog-content"><div class="section-heading">${statusBadge(t)}<span class="muted">今天 ${t.time}</span></div>${t.status==='running'?'<div class="detail-progress">'+progress(t.progress,t.stage)+'</div>':''}${t.error?`<div class="notice error"><h3>失败原因</h3><p>${esc(t.error)}</p>${button('复制错误','copy-error','copy','subtle small',`data-id="${t.id}"`)}</div>`:''}${t.status==='paused'?'<div class="notice">恢复后将从头执行本次任务。</div>':''}<section class="detail-group"><h3>执行记录</h3><dl><div><dt>执行尝试</dt><dd>第 ${t.attempt||1} 次</dd></div><div><dt>总耗时</dt><dd class="mono">${t.duration}</dd></div></dl><ol class="timeline"><li><span class="mono">${t.time}</span><span>任务已创建</span></li></ol></section><section class="detail-group"><h3>输入配置</h3><dl><div><dt>基础模型</dt><dd>${t.model}</dd></div><div><dt>输出尺寸</dt><dd class="mono">${t.size}</dd></div><div><dt>${t.kind==='lora'?'训练步数':'生成数量'}</dt><dd>${t.count} ${unit(t)}</dd></div><div><dt>${t.kind==='lora'?'学习率':'采样器'}</dt><dd class="mono">${t.kind==='lora'?'0.0001':'DPM++ 2M · Karras'}</dd></div></dl>${t.kind!=='lora'?`<details><summary>提示词与采样参数</summary><div class="prompt">${esc(t.name)}, soft natural light, detailed composition, cinematic colors</div><dl><div><dt>采样步数</dt><dd>30</dd></div><div><dt>CFG</dt><dd>7.0</dd></div><div><dt>Seed</dt><dd class="mono">284197632</dd></div></dl></details>`:'<dl><div><dt>训练样本</dt><dd>24 组图片与 Caption</dd></div><div><dt>Rank / Alpha</dt><dd class="mono">32 / 16</dd></div></dl>'}</section><section class="detail-group"><h3>${t.kind==='lora'?'模型产物':'生成结果'}</h3>${t.output?`<div class="result-list">${Array.from({length:t.output},(_,i)=>`<div class="result-row">${icon(t.kind==='lora'?'layers':'image')}<span class="mono">${t.kind==='lora'?`${t.project}-epoch-${(i+1)*4}.safetensors`:`${t.id}-${String(i+1).padStart(3,'0')}.png`}</span><span class="muted">${t.kind==='lora'?'218 MB':t.size}</span></div>`).join('')}</div>`:'<p class="muted">尚无输出结果</p>'}</section></div><div class="dialog-footer"><div>${actions(t)}</div>${t.mode==='generation'&&isTerminal(t)?button('删除任务','delete','trash','danger',`data-id="${t.id}"`):''}</div>`;if(!detail.open)detail.showModal();}
function closeDetail(){const id=detailId;detail.close();detailId=null;const target=returnFocus?.isConnected?returnFocus:document.querySelector(`[data-detail="${id}"]`);(target||document.querySelector("#search"))?.focus();}
function ask(title,text,onConfirm,label='确认'){confirmDialog.innerHTML=`<div class="dialog-header"><h2 id="confirm-title">${title}</h2></div><div class="dialog-content"><p>${text}</p></div><div class="dialog-footer">${button('返回','dismiss-confirm',null,'subtle')}${button(label,'accept-confirm',null,'danger')}</div>`;confirmDialog.showModal();confirmDialog.querySelector('[data-action="accept-confirm"]').onclick=()=>{confirmDialog.close();onConfirm();};}
function setStatus(t,next){selected.delete(t.id);t.status=next;t.error=undefined;render();if(detail.open)openDetail(t.id);toast(`${t.name}：${states[next]}`);}
function removeTasks(ids){const names=ids.map(id=>tasks.find(t=>t.id===id)).filter(t=>t&&t.mode==="generation"&&isTerminal(t));if(names.length!==ids.length||!names.length){selected.clear();render();toast("仅可删除生产模块的终态任务，请重新选择。");return;}ask(`删除 ${names.length} 项任务？`,`${names.map(t=>esc(t.name)).join('、')}。任务记录、输入快照与其 ${names.reduce((n,t)=>n+t.output,0)} 张结果图片将被永久删除，无法恢复。`,()=>{for(const t of names){if(t.mode!=="generation"||!isTerminal(t))continue;tasks.splice(tasks.indexOf(t),1);}selected.clear();if(detail.open)closeDetail();render();toast(`已删除 ${names.length} 项任务`);},'永久删除');}
document.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.detail){openDetail(target.dataset.detail);return;}const action=target.dataset.action,t=tasks.find(t=>t.id===target.dataset.id);switch(action){case'theme':document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';localStorage.setItem('task-workspace-theme',document.body.dataset.theme);render();break;case'reset':query=project=status=kind=period='';selected.clear();render();break;case'close-detail':closeDetail();break;case'dismiss-confirm':confirmDialog.close();break;case'pause':ask('暂停这次生成？','当前生成将停止。恢复后会从头执行本次任务。',()=>setStatus(t,'paused'),'暂停任务');break;case'cancel':ask('取消任务？',`“${esc(t.name)}”将停止执行，已有结果仍可查看。`,()=>setStatus(t,'cancelled'),'取消任务');break;case'resume':case'retry':{if(t.kind==='lora'&&tasks.some(x=>x.kind==='lora'&&activeStates.includes(x.status))){toast('已有等待中的训练运行，请先取消它再重新训练。');break;}t.attempt=(t.attempt||1)+1;setStatus(t,'queued');break;}case'copy-error':try{await navigator.clipboard.writeText(t.error);toast('错误信息已复制');}catch{toast('复制失败，请选择错误文本手动复制');}break;case'delete':removeTasks([t.id]);break;case'delete-selected':removeTasks([...selected]);break;case'clear-selection':selected.clear();updateContent();break;}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;selected.clear();const position=e.target.selectionStart;updateContent();const field=document.querySelector('#search');field.focus();field.setSelectionRange(position,position);}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.select){el.checked?selected.add(el.dataset.select):selected.delete(el.dataset.select);updateContent();return;}if(el.id==='select-all'){selected=new Set(el.checked?tasks.filter(t=>matching(t)&&isTerminal(t)&&(!status||t.status===status)).map(t=>t.id):[]);updateContent();return;}if(el.id==='project')project=el.value;else if(el.id==='status')status=el.value;else if(el.id==='kind')kind=el.value;else if(el.id==='period')period=el.value;else if(el.id==='order')order=el.value;else return;selected.clear();updateContent();document.getElementById(el.id)?.focus();});
window.addEventListener('hashchange',()=>{mode=location.hash==='#training'?'training':'generation';query=project=status=kind=period='';selected.clear();if(detail.open)closeDetail();render();});
detail.addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
for(const dialog of [detail,confirmDialog])dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){if(dialog===detail)closeDetail();else dialog.close();}}});
render();
